---
title: "Hands-on Exercise 6b: Local Measures of Spatial Autocorrelation"
author: "Andrew Huang"
date: "2026-09-24"
date-modified: "last-modified"
format: html
execute:
  warning: false
  freeze: auto
---

## Getting started

```{r}
pacman::p_load(sf, sfdep, tmap, tidyverse)
```

## Importing data

```{r}
hunan <- st_read(dsn = "data/geospatial", layer = "Hunan") %>%
  st_transform(crs = 32650)
hunan2012 <- read_csv("data/aspatial/Hunan_2012.csv")
```

```{r}
hunan <- left_join(hunan, hunan2012) %>%
  select(1:4, 7, 15)
```

## Mapping GDPPC

```{r fig.width=10}
equal <- tm_shape(hunan) +
  tm_polygons(fill = "GDPPC",
              fill.scale = tm_scale_intervals(
                style = "equal",
                n = 5,
                values = "brewer.blues"),
              fill.legend = tm_legend(
                title = "GDPPC",
                position = tm_pos_in("left", "bottom"))) +
  tm_borders(fill_alpha = 0.5) +
  tm_title("Equal interval classification")

quantile <- tm_shape(hunan) +
  tm_polygons(fill = "GDPPC",
              fill.scale = tm_scale_intervals(
                style = "quantile",
                n = 5,
                values = "brewer.blues"),
              fill.legend = tm_legend(
                title = "GDPPC",
                position = tm_pos_in("left", "bottom"))) +
  tm_borders(fill_alpha = 0.5) +
  tm_title("Quantile classification")

tmap_arrange(equal, quantile, asp = 1, ncol = 2)
```

## Local Moran's I

```{r}
wm_q <- hunan %>%
  mutate(nb = st_contiguity(geometry),
         wt = st_weights(nb, style = "W"),
         .before = 1)

summary(wm_q$nb)
```

```{r}
set.seed(1234)

lisa <- wm_q %>%
  mutate(local_moran = local_moran(GDPPC, nb, wt, nsim = 99),
         .before = 1) %>%
  unnest(local_moran)
```

```{r fig.width=10}
tm_shape(lisa) +
  tm_polygons(fill = "ii",
              fill.scale = tm_scale_intervals(
                style = "pretty",
                n = 5,
                values = "brewer.RdBu"),
              fill.legend = tm_legend(
                title = "Local Moran's I",
                position = tm_pos_out())) +
  tm_borders(fill_alpha = 0.5) +
  tm_title("Local Moran's I of GDPPC (Queen's method)")
```

```{r fig.width=10}
tm_shape(lisa) +
  tm_polygons(fill = "p_ii",
              fill.scale = tm_scale_intervals(
                breaks = c(-Inf, 0.001, 0.01, 0.05, 0.1, Inf),
                values = "-brewer.Reds"),
              fill.legend = tm_legend(
                title = "p-value",
                position = tm_pos_out())) +
  tm_borders(fill_alpha = 0.5) +
  tm_title("p-values of local Moran's I of GDPPC (Queen's method)")
```

## Moran scatterplot

```{r}
lisa <- lisa %>%
  mutate(lag_GDPPC = st_lag(GDPPC, nb, wt),
         .before = 1) %>%
  unnest(lag_GDPPC)
```

```{r}
ggplot(data = lisa, aes(x = GDPPC, y = lag_GDPPC, color = mean)) +
  geom_point(size = 2) +
  geom_smooth(method = "lm", se = FALSE, color = "black") +
  geom_hline(yintercept = mean(lisa$lag_GDPPC), lty = 2) +
  geom_vline(xintercept = mean(lisa$GDPPC), lty = 2) +
  scale_color_manual(values = c("High-High" = "red",
                                 "Low-Low" = "blue",
                                 "Low-High" = "lightblue",
                                 "High-Low" = "pink")) +
  labs(x = "GDPPC", y = "Spatial Lag of GDPPC",
       title = "Moran Scatterplot with LISA Quadrants") +
  theme_minimal()
```

## LISA cluster map

```{r}
lisa <- lisa %>%
  mutate(
    LISA_cluster = ifelse(p_ii < 0.05, as.character(mean), "Insignificant"),
    LISA_cluster = factor(LISA_cluster,
                           levels = c("Insignificant", "Low-Low", "Low-High",
                                      "High-Low", "High-High")))
```

```{r fig.width=10}
tm_shape(lisa) +
  tm_polygons(
    fill = "LISA_cluster",
    fill.scale = tm_scale_categorical(
      values = c("grey80", "blue", "lightblue", "pink", "red")),
    fill.legend = tm_legend(
      title = "LISA Cluster",
      position = tm_pos_in("left", "bottom"))) +
  tm_borders() +
  tm_title("Local Moran's I Clusters (p < 0.05)")
```

## Hot spot and cold spot analysis (Gi*)

```{r}
ct <- critical_threshold(st_geometry(hunan))
ct
```

```{r}
hunan_fdw <- hunan %>%
  mutate(nb = include_self(st_dist_band(st_geometry(geometry), upper = ct)),
         wt = st_weights(nb, style = "W"),
         .before = 1)
```

```{r}
HCSA_fdw <- hunan_fdw %>%
  mutate(gistar = local_gstar_perm(GDPPC, nb, wt, nsim = 99),
         .before = 1) %>%
  unnest(gistar)
```

```{r fig.width=10}
tm_shape(HCSA_fdw) +
  tm_polygons(fill = "gi_star",
              fill.scale = tm_scale_intervals(
                style = "pretty",
                n = 6,
                values = "brewer.rd_bu"),
              fill.legend = tm_legend(
                title = "Gi*",
                position = tm_pos_out())) +
  tm_borders(fill_alpha = 0.5) +
  tm_title(paste0("Gi* of GDPPC (Fixed Bandwidth d = ", round(ct, 2), "m)"))
```

## HCSA cluster map

```{r}
HCSA_fdw <- HCSA_fdw %>%
  mutate(HCSA_cluster = case_when(
    p_sim > 0.05 ~ "Insignificant",
    p_sim <= 0.05 & cluster == "High" ~ "Hot spot",
    p_sim <= 0.05 & cluster == "Low"  ~ "Cold spot",
    TRUE ~ "Other"),
    HCSA_cluster = factor(HCSA_cluster,
                           levels = c("Insignificant", "Hot spot", "Cold spot")),
    .before = 1)
```

```{r fig.width=10}
tm_shape(HCSA_fdw) +
  tm_polygons(
    fill = "HCSA_cluster",
    fill.scale = tm_scale_categorical(values = c("grey80", "red", "blue")),
    fill.legend = tm_legend(
      title = "HCSA Cluster",
      position = tm_pos_in("left", "bottom"))) +
  tm_borders() +
  tm_title("HCSA Clusters (p < 0.05)")
```
