project:
  type: website
  render:
    - "*.qmd"
    - "Hands-on_Ex/**/*.qmd"
    - "Take-home_Ex/**/*.qmd"
    - "inclass_Ex/**/*.qmd"

website:
  title: "Huang Kang-Chih | Geospatial"
  navbar:
    left:
      - href: index.qmd
        text: Home

      - text: "Hands-on Exercise"
        menu:
          - href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd
            text: "Ex01: Geospatial Data Science with R"
          - href: Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.qmd
            text: "Ex02: Thematic Mapping & GeoVisualisation"
          - href: Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.qmd
            text: "Ex03: Point Pattern Analysis"
          - href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.qmd
            text: "Ex04: Spatio-Temporal Point Pattern Analysis"
          - href: Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.qmd
            text: "Ex05: Spatial Weights and Applications"

      - text: "Take-home Exercise"
        menu:
          - href: Take-home_Ex/Take-home_Ex01/index.qmd
            text: "Ex01: Thailand Road Accident Spatio-temporal Analysis"

      - text: "In-class Exercise"
        menu:
          - href: "inclass_Ex/inclass week 4/inclass week 4.qmd"
            text: "Ex04: Spatial Weights and Applications"

      - href: about.qmd
        text: About

format:
  html:
    theme: litera
    toc: true
    css: styles.css

execute:
  freeze: auto
