<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Andrew Huang">
<meta name="dcterms.date" content="2026-09-10">

<title>Hands-on Exercise 4: Spatio-Temporal Point Pattern Analysis – Huang Kang-Chih | Geospatial</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-e5f91ad3aecf1eb9d35c53ff38ad6c57.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Huang Kang-Chih | Geospatial</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html">
 <span class="dropdown-text">Ex01: Geospatial Data Science with R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html">
 <span class="dropdown-text">Ex02: Thematic Mapping &amp; GeoVisualisation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html">
 <span class="dropdown-text">Ex03: Point Pattern Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html">
 <span class="dropdown-text">Ex04: Spatio-Temporal Point Pattern Analysis</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex01/index.html">
 <span class="dropdown-text">Ex01: Thailand Road Accident Spatio-temporal Analysis</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link active" data-scroll-target="#getting-started">Getting started</a></li>
  <li><a href="#importing-and-preparing-the-data" id="toc-importing-and-preparing-the-data" class="nav-link" data-scroll-target="#importing-and-preparing-the-data">Importing and preparing the data</a></li>
  <li><a href="#visualising-the-fire-points" id="toc-visualising-the-fire-points" class="nav-link" data-scroll-target="#visualising-the-fire-points">Visualising the fire points</a></li>
  <li><a href="#converting-to-spatstats-ppp-format" id="toc-converting-to-spatstats-ppp-format" class="nav-link" data-scroll-target="#converting-to-spatstats-ppp-format">Converting to spatstat’s ppp format</a></li>
  <li><a href="#part-1-spatio-temporal-kde-does-the-hot-spot-move-over-the-year" id="toc-part-1-spatio-temporal-kde-does-the-hot-spot-move-over-the-year" class="nav-link" data-scroll-target="#part-1-spatio-temporal-kde-does-the-hot-spot-move-over-the-year">Part 1 — Spatio-temporal KDE: does the hot spot move over the year?</a></li>
  <li><a href="#part-2-bootstrap-bandwidth-selection" id="toc-part-2-bootstrap-bandwidth-selection" class="nav-link" data-scroll-target="#part-2-bootstrap-bandwidth-selection">Part 2 — Bootstrap bandwidth selection</a></li>
  <li><a href="#part-3-space-time-k-function-is-the-clustering-statistically-real" id="toc-part-3-space-time-k-function-is-the-clustering-statistically-real" class="nav-link" data-scroll-target="#part-3-space-time-k-function-is-the-clustering-statistically-real">Part 3 — Space-time K-function: is the clustering statistically real?</a></li>
  <li><a href="#notes-and-open-questions" id="toc-notes-and-open-questions" class="nav-link" data-scroll-target="#notes-and-open-questions">Notes and open questions</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Hands-on Exercise 4: Spatio-Temporal Point Pattern Analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Andrew Huang </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 10, 2026</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">September 10, 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="getting-started" class="level2">
<h2 class="anchored" data-anchor-id="getting-started">Getting started</h2>
<p>Ex03 was all first- and second-order analysis on a single snapshot in time — preschools just sitting there, no clock attached. This one adds the missing dimension: the density itself changes as time moves. Instead of one KDE surface, you get a stack of them, one per moment, and the interesting question becomes whether the hot spot actually travels or just sits still.</p>
<p>New package this time is <code>sparr</code>, which is built specifically for this — <code>spattemp.density()</code> gives a spatio-temporal KDE in one call, <code>BOOT.spattemp()</code> picks the bandwidths for you instead of guessing.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, spatstat, sparr, stpp, tmap, tidyverse, lubridate)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>stpp</code> and <code>tmap</code> are both new installs tonight — didn’t have them on this laptop before, and <code>stpp</code> in particular dragged in <code>rpanel</code>/<code>splancs</code> as dependencies, which took a bit to sort out. So the two sections further down that use them hadn’t actually been run before this render — wrote that code straight off the package documentation (checked the actual <code>STIKhat</code>/<code>as.3dpoints</code>/<code>tm_shape</code> signatures, not guessing), but didn’t have a confirmed working render until just now.</p>
<p>Data honesty note, upfront: the textbook chapter uses <code>forestfires.csv</code> — FIRMS MODIS fire detections for Indonesia, 2023, cropped to Kepulauan Bangka Belitung — plus a sub-district (kelurahan) boundary from Indonesia’s own geospatial portal. Neither file is on eLearn, and FIRMS’s own download tool turned out to be more fight than it was worth with this due tomorrow. What I used instead: a real MODIS active-fire archive, bulk-downloaded and split by country and year, and I pulled the 2023 Indonesia file out of it — so the year actually matches the chapter now, it’s genuinely 2023 satellite detections. The one thing still substituted is the boundary: I used geoBoundaries’ regency-level (ADM2) polygons for Bangka Belitung’s 7 regencies instead of the finer kelurahan shapefile, since I couldn’t track that one down either. Same region, same year, same method — just a coarser administrative boundary than the chapter’s. Flagging it here rather than letting it look like the exact original file.</p>
</section>
<section id="importing-and-preparing-the-data" class="level2">
<h2 class="anchored" data-anchor-id="importing-and-preparing-the-data">Importing and preparing the data</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>bb_raw <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"data/geospatial/BangkaBelitung.geojson"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `BangkaBelitung' from data source 
  `C:\Users\User\Desktop\Geospatial\Hands-on_Ex\Hands-on_Ex04\data\geospatial\BangkaBelitung.geojson' 
  using driver `GeoJSON'
Simple feature collection with 7 features and 5 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 105.1084 ymin: -3.416903 xmax: 108.848 ymax: -1.501884
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
<p>Same move as Ex03’s <code>st_union()</code> on the subzones: 7 separate regency polygons get dissolved into one outline for the whole island group, then reprojected to UTM zone 48S (EPSG:32748) — that’s the metric CRS the chapter uses for this part of Indonesia.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>bb_sf <span class="ot">&lt;-</span> bb_raw <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_union</span>() <span class="sc">%&gt;%</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_sf</span>() <span class="sc">%&gt;%</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">32748</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">st_geometry</span>(bb_sf))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands-on_Ex04_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>That’s Bangka on the left, Belitung on the right, plus a scatter of small islands around both — matches what Bangka Belitung actually looks like on a map, which was a decent sanity check that the regency list was right.</p>
<p>Fire data next. Raw CSV has one row per detection with <code>latitude</code>/<code>longitude</code>/<code>acq_date</code> among other columns (brightness, confidence, satellite — not using those here). Converting to <code>sf</code> points, reprojecting to match the boundary, then pulling out day-of-year and month since <code>spattemp.density()</code> needs a numeric time mark, not a date.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>fires <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/aspatial/forestfires_2023.csv"</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>fires_sf <span class="ot">&lt;-</span> fires <span class="sc">%&gt;%</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>(<span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"longitude"</span>, <span class="st">"latitude"</span>), <span class="at">crs =</span> <span class="dv">4326</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">32748</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">acq_date =</span> <span class="fu">as.Date</span>(acq_date),</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">DayofYear =</span> <span class="fu">yday</span>(acq_date),</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Month_num =</span> <span class="fu">month</span>(acq_date),</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">Month_fac =</span> <span class="fu">factor</span>(month.name[Month_num], <span class="at">levels =</span> month.name)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(fires_sf)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4119</code></pre>
</div>
</div>
<p>4,119 points inside the bounding box I filtered the country file down to before ever touching R. That box is generous though — wider than the actual island outline — so a fair number of these will fall in open water once checked against the real polygon.</p>
</section>
<section id="visualising-the-fire-points" class="level2">
<h2 class="anchored" data-anchor-id="visualising-the-fire-points">Visualising the fire points</h2>
<p>Before jumping into any density estimate, the chapter’s own move is to just look at where the dots land — <code>tmap</code> instead of base R plotting since it handles the sf objects directly and facets by month in one call.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(bb_sf) <span class="sc">+</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>() <span class="sc">+</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(fires_sf) <span class="sc">+</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands-on_Ex04_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(bb_sf) <span class="sc">+</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>() <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(fires_sf) <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">size =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_facets</span>(<span class="at">by =</span> <span class="st">"Month_fac"</span>, <span class="at">free.coords =</span> <span class="cn">FALSE</span>, <span class="at">drop.units =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands-on_Ex04_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Should visually confirm the same thing Part 1’s KDE finds below — empty months at the start of the year, dots piling up around July–September.</p>
</section>
<section id="converting-to-spatstats-ppp-format" class="level2">
<h2 class="anchored" data-anchor-id="converting-to-spatstats-ppp-format">Converting to spatstat’s ppp format</h2>
<p>Same <code>ppp</code> + <code>owin</code> combination as Ex03, marks this time being <code>DayofYear</code> instead of nothing, since the whole point of this exercise is keeping the time dimension attached to every point.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>bb_owin <span class="ot">&lt;-</span> <span class="fu">as.owin</span>(bb_sf)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>co <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(fires_sf)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>fires_ppp <span class="ot">&lt;-</span> <span class="fu">ppp</span>(co[, <span class="dv">1</span>], co[, <span class="dv">2</span>], <span class="at">window =</span> bb_owin, <span class="at">marks =</span> fires_sf<span class="sc">$</span>DayofYear)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>fires_ppp <span class="ot">&lt;-</span> fires_ppp[bb_owin]</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>fires_ppp<span class="sc">$</span>n</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 899</code></pre>
</div>
</div>
<p>899 left out of 4,119 — a bigger drop than I expected, 3,220 points gone. Part of that’s just the loose bounding-box filter doing its job. But it’s also a bigger fraction than felt right at first, so I checked: some of it is almost certainly real MODIS detections sitting just offshore, not on land at all — Bangka is known for offshore tin dredging, and dredge platforms/mining barges run hot enough that MODIS’s fire-detection algorithm can flag them the same way it flags an actual fire. Worth keeping in mind reading the “fire” density below — a slice of what MODIS calls a fire pixel here is plausibly mining activity, not vegetation burning, and that’s a property of the <em>sensor</em>, not something specific to my substitute boundary.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fires_ppp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Marked planar point pattern:  899 points
Average intensity 5.380728e-08 points per square unit

Coordinates are given to 10 decimal places

marks are numeric, of type 'double'
Summary:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   10.0   219.0   260.0   247.7   288.0   360.0 

Window: polygonal boundary
166 separate polygons (no holes)
             vertices        area relative.area
polygon 1         972 1.15518e+10      6.91e-01
polygon 2           4 5.52353e+04      3.31e-06
polygon 3           4 2.71303e+05      1.62e-05
polygon 4           7 1.22230e+06      7.32e-05
polygon 5          11 1.19865e+06      7.17e-05
polygon 6           5 1.61208e+05      9.65e-06
polygon 7           7 9.72385e+04      5.82e-06
polygon 8           5 8.01867e+04      4.80e-06
polygon 9           5 1.15109e+05      6.89e-06
polygon 10          6 2.82441e+05      1.69e-05
polygon 11          4 1.61748e+05      9.68e-06
polygon 12          5 9.62914e+04      5.76e-06
polygon 13          8 1.38438e+05      8.29e-06
polygon 14         16 3.15251e+06      1.89e-04
polygon 15         10 2.30273e+06      1.38e-04
polygon 16          3 4.93646e+04      2.95e-06
polygon 17          4 4.39216e+04      2.63e-06
polygon 18          3 5.15383e+04      3.08e-06
polygon 19          3 8.61068e+03      5.15e-07
polygon 20        750 4.61633e+09      2.76e-01
polygon 21          4 5.82890e+04      3.49e-06
polygon 22          3 1.79418e+04      1.07e-06
polygon 23          4 6.61881e+04      3.96e-06
polygon 24          8 1.44528e+06      8.65e-05
polygon 25          3 1.34860e+04      8.07e-07
polygon 26          3 1.63158e+04      9.77e-07
polygon 27          4 6.47358e+04      3.87e-06
polygon 28          3 1.43257e+04      8.57e-07
polygon 29          3 2.11344e+04      1.26e-06
polygon 30          7 1.83485e+05      1.10e-05
polygon 31          3 2.07092e+04      1.24e-06
polygon 32          3 1.21024e+04      7.24e-07
polygon 33          3 1.25179e+04      7.49e-07
polygon 34          3 1.48894e+04      8.91e-07
polygon 35          5 7.22322e+04      4.32e-06
polygon 36          4 7.47054e+04      4.47e-06
polygon 37          3 3.32508e+04      1.99e-06
polygon 38          5 2.15573e+05      1.29e-05
polygon 39         10 1.14421e+06      6.85e-05
polygon 40          4 1.97234e+05      1.18e-05
polygon 41          3 3.29659e+04      1.97e-06
polygon 42          3 1.85400e+04      1.11e-06
polygon 43         12 2.22646e+06      1.33e-04
polygon 44          3 2.85195e+04      1.71e-06
polygon 45          5 8.03029e+04      4.81e-06
polygon 46          3 2.36333e+04      1.41e-06
polygon 47          7 5.03517e+05      3.01e-05
polygon 48          4 4.95921e+04      2.97e-06
polygon 49          4 6.50527e+04      3.89e-06
polygon 50         12 1.03324e+06      6.18e-05
polygon 51          7 2.14381e+05      1.28e-05
polygon 52          4 3.35785e+04      2.01e-06
polygon 53          7 8.43923e+05      5.05e-05
polygon 54          5 9.12163e+04      5.46e-06
polygon 55         13 3.89789e+05      2.33e-05
polygon 56          3 1.99295e+04      1.19e-06
polygon 57          6 9.27007e+04      5.55e-06
polygon 58          6 3.14806e+04      1.88e-06
polygon 59          7 3.87331e+05      2.32e-05
polygon 60          5 4.15080e+05      2.48e-05
polygon 61         47 1.77006e+07      1.06e-03
polygon 62          4 2.17224e+05      1.30e-05
polygon 63          4 8.11440e+04      4.86e-06
polygon 64         98 4.78925e+07      2.87e-03
polygon 65        112 1.19531e+08      7.15e-03
polygon 66         18 3.69323e+06      2.21e-04
polygon 67          4 8.13274e+04      4.87e-06
polygon 68          6 6.68740e+04      4.00e-06
polygon 69          4 2.78888e+04      1.67e-06
polygon 70          4 2.89101e+04      1.73e-06
polygon 71          8 1.41673e+06      8.48e-05
polygon 72         15 3.74263e+06      2.24e-04
polygon 73         13 3.64500e+06      2.18e-04
polygon 74          3 1.61822e+04      9.69e-07
polygon 75          7 2.14775e+05      1.29e-05
polygon 76         19 7.09955e+06      4.25e-04
polygon 77          8 1.73607e+05      1.04e-05
polygon 78          7 2.05677e+06      1.23e-04
polygon 79        105 2.13014e+08      1.27e-02
polygon 80          5 1.76854e+05      1.06e-05
polygon 81          9 1.59859e+06      9.57e-05
polygon 82          3 3.15646e+04      1.89e-06
polygon 83         61 2.25281e+07      1.35e-03
polygon 84         16 2.43687e+06      1.46e-04
polygon 85          3 2.65057e+04      1.59e-06
polygon 86          3 1.25332e+04      7.50e-07
polygon 87          6 5.54606e+05      3.32e-05
polygon 88          6 1.05070e+06      6.29e-05
polygon 89          7 4.10680e+05      2.46e-05
polygon 90          5 3.21451e+05      1.92e-05
polygon 91         10 1.15656e+06      6.92e-05
polygon 92          4 5.09016e+04      3.05e-06
polygon 93          4 5.37866e+04      3.22e-06
polygon 94          4 4.59354e+04      2.75e-06
polygon 95          4 2.11056e+04      1.26e-06
polygon 96          4 2.48302e+04      1.49e-06
polygon 97         15 5.16472e+06      3.09e-04
polygon 98         19 1.77557e+06      1.06e-04
polygon 99          4 3.18341e+04      1.91e-06
polygon 100        12 3.07555e+06      1.84e-04
polygon 101         4 1.39730e+05      8.36e-06
polygon 102         7 4.57652e+05      2.74e-05
polygon 103         3 4.35533e+04      2.61e-06
polygon 104         4 9.95883e+04      5.96e-06
polygon 105         4 8.39710e+04      5.03e-06
polygon 106         8 1.31312e+06      7.86e-05
polygon 107         5 2.09401e+05      1.25e-05
polygon 108         3 1.21280e+04      7.26e-07
polygon 109         7 1.85681e+06      1.11e-04
polygon 110         4 4.31833e+04      2.58e-06
polygon 111         7 6.60441e+05      3.95e-05
polygon 112         7 8.15940e+05      4.88e-05
polygon 113        14 3.96656e+06      2.37e-04
polygon 114         8 4.31229e+05      2.58e-05
polygon 115         4 3.76481e+04      2.25e-06
polygon 116         6 7.23993e+05      4.33e-05
polygon 117         4 3.08229e+05      1.84e-05
polygon 118         3 2.06334e+04      1.23e-06
polygon 119        23 7.36520e+06      4.41e-04
polygon 120         5 2.32145e+05      1.39e-05
polygon 121         4 3.82403e+04      2.29e-06
polygon 122         3 6.07853e+04      3.64e-06
polygon 123         4 5.72581e+04      3.43e-06
polygon 124         3 1.48414e+04      8.88e-07
polygon 125         4 3.66299e+05      2.19e-05
polygon 126         3 4.65963e+04      2.79e-06
polygon 127        15 3.92372e+06      2.35e-04
polygon 128         5 4.33959e+05      2.60e-05
polygon 129         6 4.96159e+05      2.97e-05
polygon 130         4 6.68707e+04      4.00e-06
polygon 131         3 2.99676e+04      1.79e-06
polygon 132        14 1.25380e+06      7.50e-05
polygon 133         6 7.55594e+05      4.52e-05
polygon 134         4 1.65543e+05      9.91e-06
polygon 135         8 2.82780e+05      1.69e-05
polygon 136         5 3.90974e+05      2.34e-05
polygon 137        27 1.62599e+07      9.73e-04
polygon 138        12 1.39947e+06      8.38e-05
polygon 139         8 2.21254e+06      1.32e-04
polygon 140         3 1.57797e+04      9.44e-07
polygon 141         8 1.15978e+06      6.94e-05
polygon 142         3 3.33351e+04      2.00e-06
polygon 143         4 1.06614e+05      6.38e-06
polygon 144         6 4.37427e+04      2.62e-06
polygon 145         6 4.83872e+05      2.90e-05
polygon 146         4 9.23055e+04      5.52e-06
polygon 147         7 3.71832e+05      2.23e-05
polygon 148        15 3.38528e+06      2.03e-04
polygon 149         3 2.50495e+04      1.50e-06
polygon 150         4 2.52480e+04      1.51e-06
polygon 151         5 1.67399e+05      1.00e-05
polygon 152         4 1.13606e+05      6.80e-06
polygon 153         5 5.04469e+04      3.02e-06
polygon 154        13 2.23775e+06      1.34e-04
polygon 155         4 6.37252e+04      3.81e-06
polygon 156        12 1.02457e+06      6.13e-05
polygon 157         4 8.79862e+04      5.27e-06
polygon 158         4 1.66575e+05      9.97e-06
polygon 159         6 2.60576e+05      1.56e-05
polygon 160         3 1.92124e+04      1.15e-06
polygon 161         4 6.06838e+04      3.63e-06
polygon 162         9 1.14617e+06      6.86e-05
polygon 163         4 1.58161e+04      9.47e-07
polygon 164         4 1.29217e+05      7.73e-06
polygon 165         6 2.02654e+05      1.21e-05
polygon 166         3 1.06955e+05      6.40e-06
enclosing rectangle: [512053.7, 928099.7] x [9621818, 9833975] units
                     (416000 x 212200 units)
Window area = 16707800000 square units
Fraction of frame area: 0.189</code></pre>
</div>
</div>
</section>
<section id="part-1-spatio-temporal-kde-does-the-hot-spot-move-over-the-year" class="level2">
<h2 class="anchored" data-anchor-id="part-1-spatio-temporal-kde-does-the-hot-spot-move-over-the-year">Part 1 — Spatio-temporal KDE: does the hot spot move over the year?</h2>
<p><code>spattemp.density()</code> does the trivariate smoothing — two spatial dimensions plus time — and picks its own bandwidths by default the same way <code>bw.ppl()</code> etc. did in Ex03, just for three dimensions instead of two.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>st_kde <span class="ot">&lt;-</span> <span class="fu">spattemp.density</span>(fires_ppp)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>st_kde</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Spatiotemporal Kernel Density Estimate

Bandwidths
  h = 19155.99 (spatial)
  lambda = 6.4456 (temporal)

No. of observations
  899 </code></pre>
</div>
</div>
<p>Default spatial bandwidth landed around 19.2km, temporal around 6.4 days — tighter spatially than I expected, but still wide relative to the year. Plotting six snapshots across the year, fixing the colour scale so the panels are actually comparable to each other:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>tims <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">30</span>, <span class="dv">120</span>, <span class="dv">213</span>, <span class="dv">244</span>, <span class="dv">274</span>, <span class="dv">300</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfcol =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>))</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> tims) {</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(st_kde, i, <span class="at">override.par =</span> <span class="cn">FALSE</span>, <span class="at">fix.range =</span> <span class="cn">TRUE</span>, <span class="at">main =</span> <span class="fu">paste0</span>(<span class="st">"Day "</span>, i))</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands-on_Ex04_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Days 30 and 120 (January, April/May) are flat — nothing burning yet. Day 213 (start of August) is when a hot spot appears on the northwest side of Bangka, and it just keeps intensifying from there: day 244 (start of September) it’s spread across western Bangka and reached Belitung, and by day 274–300 (start of October through late October) western Bangka is lit up as bright as this dataset gets. Checking the raw monthly counts backs this up — September and October alone account for 1,395 and 1,882 of the 4,119 detections respectively, versus single or low double digits from January through April. 2023 was an El Niño year in Indonesia, so a fire season this late and this intense tracks with what actually happened — the dry season ran longer and worse than a typical year, and that shows up here without me having to argue for it.</p>
</section>
<section id="part-2-bootstrap-bandwidth-selection" class="level2">
<h2 class="anchored" data-anchor-id="part-2-bootstrap-bandwidth-selection">Part 2 — Bootstrap bandwidth selection</h2>
<p>Default bandwidths above were picked automatically, but <code>sparr</code> has a proper optimiser for the spatio-temporal case — <code>BOOT.spattemp()</code>, doing for two bandwidths at once roughly what <code>bw.diggle</code> etc. did for one in Ex03. Fair warning: this one’s slow, close to a minute even on a fairly small point set, since it’s bootstrapping over both dimensions together.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>bw_boot <span class="ot">&lt;-</span> <span class="fu">BOOT.spattemp</span>(fires_ppp, <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>bw_boot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>          h      lambda 
21909.02939    19.78252 </code></pre>
</div>
</div>
<p>Spatial bandwidth barely moved (about 21.9km vs.&nbsp;19.2km default), but the temporal one changed a lot — around 19.8 days instead of 6.4. Re-running the density with those and plotting the same six days:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>st_kde_opt <span class="ot">&lt;-</span> <span class="fu">spattemp.density</span>(fires_ppp, <span class="at">h =</span> bw_boot[<span class="st">"h"</span>], <span class="at">lambda =</span> bw_boot[<span class="st">"lambda"</span>])</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfcol =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>))</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> tims) {</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(st_kde_opt, i, <span class="at">override.par =</span> <span class="cn">FALSE</span>, <span class="at">fix.range =</span> <span class="cn">TRUE</span>, <span class="at">main =</span> <span class="fu">paste0</span>(<span class="st">"Day "</span>, i))</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands-on_Ex04_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Same overall story, smoother picture — the western-Bangka hot spot at day 274/300 is a touch less peaky than with the default bandwidth, since a wider temporal window (19.8 days vs.&nbsp;6.4) pools in more nearby detections per snapshot. Makes each panel a less noisy estimate at the cost of blurring the day-to-day detail slightly. This is basically the 2D bandwidth-choice lesson from Ex03 again, just now there are two bandwidths to get right instead of one.</p>
</section>
<section id="part-3-space-time-k-function-is-the-clustering-statistically-real" class="level2">
<h2 class="anchored" data-anchor-id="part-3-space-time-k-function-is-the-clustering-statistically-real">Part 3 — Space-time K-function: is the clustering statistically real?</h2>
<p>Same first-order-vs-second-order distinction as Ex03: everything above (KDE, STKDE) shows <em>where and when it’s dense</em>, but doesn’t actually test whether that’s more clustered than chance would produce. <code>stpp</code>’s <code>STIKhat()</code> is the space-time equivalent of Ex03’s <code>Kest()</code>/<code>envelope()</code> — counts point pairs within a given distance <em>and</em> time gap, compares that to what’s expected under a random process.</p>
<p><code>STIKhat()</code> wants a plain <code>(x, y, t)</code> matrix, not a <code>ppp</code> — <code>as.3dpoints()</code> builds that from the same clipped points used above, so the point count here matches <code>fires_ppp$n</code> from earlier.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>xyt <span class="ot">&lt;-</span> <span class="fu">as.3dpoints</span>(fires_ppp<span class="sc">$</span>x, fires_ppp<span class="sc">$</span>y, <span class="fu">marks</span>(fires_ppp))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Leaving <code>s.region</code>/<code>t.region</code> out below, which makes <code>STIKhat()</code> fall back to the bounding box of the data and the full day-of-year range — the archipelago’s actual outline is a 166-piece multipolygon (all those small islands), and <code>STIKhat()</code> wants a single simple polygon for <code>s.region</code>, so the bounding box is the pragmatic choice here rather than something I’d want to fight with the night before this is due.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>stik <span class="ot">&lt;-</span> <span class="fu">STIKhat</span>(xyt, <span class="at">dist =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">30000</span>, <span class="dv">5000</span>), <span class="at">times =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">90</span>, <span class="dv">15</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>stpp</code> ships its own <code>plotK()</code> helper for this, and the chapter uses it — but it turns out to be broken inside a Quarto/knitr render specifically. Looked at its source after the first render came back with the K-function section silently missing (no error, just no picture): <code>plotK()</code> checks <code>dev.list()</code>, and if a graphics device is already open — which it always is mid-chunk, that’s how knitr captures plots — it closes it and calls <code>dev.new()</code> to open a fresh one. Knitr never sees that new device, so the plot draws somewhere it can’t capture, and the chunk finishes clean with nothing to show for it. Not a mistake in the code that got run, just a genuine bug in how <code>plotK()</code> behaves outside an interactive R session. Skipping it and calling <code>contour()</code> directly on the same numbers instead — <code>stik$Khat</code> and <code>stik$Ktheo</code> are exactly what <code>plotK()</code> would have plotted anyway:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contour</span>(stik<span class="sc">$</span>dist, stik<span class="sc">$</span>times, stik<span class="sc">$</span>Khat <span class="sc">-</span> stik<span class="sc">$</span>Ktheo,</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Spatial distance u (m)"</span>, <span class="at">ylab =</span> <span class="st">"Temporal distance v (days)"</span>,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Space-time L-function, Bangka Belitung 2023"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Hands-on_Ex04_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>If this is genuinely clustered in both space and time together (not just space, not just time), the contour should bulge outward at short distances and short time gaps — i.e.&nbsp;fires close in space keep showing up close in time too, past what you’d get from a homogeneous random process over the year. Worth comparing this contour against the raw monthly counts and the STKDE panels above: all three should be telling the same story if the analysis holds together.</p>
</section>
<section id="notes-and-open-questions" class="level2">
<h2 class="anchored" data-anchor-id="notes-and-open-questions">Notes and open questions</h2>
<p>Two substitutions worth restating: the fire data is genuine 2023 MODIS detections, just pulled from a bulk country archive instead of FIRMS’s own <code>forestfires.csv</code>, and the boundary is geoBoundaries’ regency-level polygons instead of the finer kelurahan shapefile the chapter uses. Couldn’t get to either original source in time, but same region, same year, same method throughout.</p>
<p>One thing worth trying later: separating out the offshore detections near Bangka’s coast before running any of this again, since a chunk of them are plausibly tin-mining heat signatures rather than actual vegetation fires — right now they’re sitting in the same point pattern as everything else. That’d also be the moment to fix <code>STIKhat()</code>’s <code>s.region</code>, which fell back to the plain bounding box instead of the archipelago’s real outline (that outline is 166 separate polygons and <code>STIKhat()</code> wants one simple one). Both of those are pulling the same direction — a decent stretch of open water is currently being counted as study area — so fixing them together would probably sharpen every result above, not just Part 3’s.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>