{
  "hash": "001ed108ab59e67ce2f97444eae2d3b4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 1: Spatio-temporal Analysis of Road Traffic Accidents\"\nsubtitle: \"First-order and second-order spatial point pattern analysis of 2022 accidents in the Bangkok Metropolitan Region\"\nauthor: \"Andrew Huang\"\ndate: \"2026-09-09\"\ndate-modified: \"last-modified\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    code-fold: false\n    code-copy: true\nexecute:\n  eval: true\n  echo: true\n  warning: false\n  message: false\n  freeze: auto\n---\n\n# Overview\n\nHands-on Exercise 3 covered spatial point pattern analysis (KDE, Clark-Evans, G/F/K/L functions) on a single static point set. This take-home exercise reuses that whole toolkit on a real dataset — road traffic accidents in Thailand — but adds a dimension Ex03 didn't touch: **time**. The dataset carries a full timestamp per accident (`incident_datetime`), so on top of \"where do accidents cluster\" I can also ask \"does *where* they cluster change depending on *when*\" — day vs. night, weekday vs. weekend.\n\nThe brief has three required parts plus one open-ended one:\n\n1. **First-order analysis** — kernel density estimation (KDE) to map accident hotspots across the study area.\n2. **Second-order analysis** — G, F, K and L functions with Monte Carlo envelopes to test whether the clustering is statistically real (i.e. not what we'd expect under complete spatial randomness, CSR).\n3. **Spatio-temporal analysis** — the dedicated technique here is spatio-temporal KDE (STKDE) via the `sparr` package, the method taught in [Chapter 6 of the course's R4GDSA reference](https://r4gdsa.netlify.app/chap06) (that chapter demonstrates it on Indonesian forest-fire data; here it's applied to accidents). On top of that I also split the pattern into discrete time periods (day/night, weekday/weekend) and run a formal Monte Carlo test for whether the spatial pattern itself differs across those splits.\n4. **Value-added analysis** — my own extension, using one of the extra attribute columns the dataset provides (`weather_condition`, `vehicle_type`, `presumed_cause`) to dig one level deeper.\n\n**Study area and scope.** The raw CSV covers the whole of Thailand from 2019–2022. The assignment only asks for the **Bangkok Metropolitan Region (BMR)** — Bangkok plus the five surrounding provinces (Nonthaburi, Pathum Thani, Samut Prakan, Nakhon Pathom, Samut Sakhon) that are conventionally grouped with it — restricted to **2022**. Filtering down to that scope is the first thing the data-preparation section below does.\n\n---\n\n# Getting Started\n\n## Packages used\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, spatstat, sparr, tidyverse, lubridate, knitr, kableExtra)\n```\n:::\n\n\n- **sf**: reading/writing vector geospatial data and all the geometric operations (projection, filtering, union).\n- **spatstat**: everything point-pattern — `ppp`, `owin`, `density()`, `envelope()`, `Gest`/`Fest`/`Kest`/`Lest`, `clarkevans.test()`, `segregation.test()`. This is the same package Ex03 used.\n- **sparr**: `spattemp.density()` — spatio-temporal kernel density estimation, the technique from Chapter 6.\n- **tidyverse** / **lubridate**: data wrangling and date-time handling.\n- **knitr** / **kableExtra**: tidy tables.\n\nUnlike Ex01/Ex02 I'm not loading `tmap` here — KDE surfaces and the G/F/K/L plots are `spatstat` objects (`im`, `fv`), and `spatstat`'s own `plot()` methods are the standard way to look at them (that's also what the lecture slides do). `ggplot2` + `sf` covers the handful of ordinary vector maps/charts I need elsewhere in this document.\n\n## Data sources\n\n| Dataset | Type | Source |\n|---|---|---|\n| `thai_road_accident_2019_2022.csv` | Aspatial (point coordinates as columns) | [Kaggle: Thailand Road Accident 2019–2022](https://www.kaggle.com/datasets/thaweewatboy/thailand-road-accident-2019-2022) |\n| Thailand ADM1 (province) boundaries | Geospatial (polygon) | [geoBoundaries](https://www.geoboundaries.org/) — `geoBoundaries-THA-ADM1` |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlist.files(\"data/geospatial\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"tha_adm1.geojson\"\n```\n\n\n:::\n\n```{.r .cell-code}\nlist.files(\"data/aspatial\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"thai_road_accident_2019_2022.csv\"    \"thai_road_accident_2019_2022.csv.gz\"\n```\n\n\n:::\n:::\n\n\n---\n\n# Importing and Preparing the Data\n\n## Geospatial: the Bangkok Metropolitan Region boundary\n\nThe accident CSV has no polygon layer of its own — it's just latitude/longitude per row — so I need an administrative boundary from elsewhere to (a) define the BMR study area and clip out-of-scope points, and (b) give `spatstat` an observation window (`owin`) to compute intensity and edge corrections against. I used geoBoundaries' Thailand province-level (ADM1) layer.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadm1 <- st_read(\"data/geospatial/tha_adm1.geojson\", quiet = TRUE)\nst_crs(adm1)$input\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"WGS 84\"\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(adm1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 77\n```\n\n\n:::\n:::\n\n\n77 provinces nationwide, in WGS84 (EPSG:4326). BMR isn't an official administrative unit in this file — it's Bangkok plus five neighbouring provinces that get treated as one metro area by convention — so I filter by name:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbmr_names <- c(\"Bangkok\", \"Nonthaburi Province\", \"Pathum Thani Province\",\n               \"Samut Prakan Province\", \"Nakhon Pathom Province\", \"Samut Sakhon Province\")\n\nbmr <- adm1 |>\n  filter(shapeName %in% bmr_names) |>\n  st_transform(32647)\n\nnrow(bmr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6\n```\n\n\n:::\n:::\n\n\n`EPSG:32647` is WGS 84 / UTM zone 47N, which covers central Thailand including Bangkok — a projected CRS with metre units, needed for any distance-based calculation (KDE bandwidths, K-function radii, etc.) later on. Working in degrees would silently distort every one of those.\n\nI also build a single dissolved polygon (`bmr_union`) — the six provinces merged into one shape with the internal borders removed. This is what becomes the `spatstat` observation window; point-pattern statistics don't care about which province a point falls in, only whether it falls inside *the* window.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbmr_union <- st_union(bmr) |> st_sf() |> st_make_valid()\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_sf(data = bmr, aes(fill = shapeName), colour = \"white\", linewidth = 0.3) +\n  geom_sf(data = bmr_union, fill = NA, colour = \"black\", linewidth = 0.8) +\n  labs(fill = \"Province\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![The Bangkok Metropolitan Region boundary used as the study area (six provinces dissolved into one polygon).](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n## Aspatial: the accident records\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc <- read_csv(\n  \"data/aspatial/thai_road_accident_2019_2022.csv\",\n  show_col_types = FALSE,\n  col_types = cols(incident_datetime = col_datetime(format = \"%Y-%m-%d %H:%M:%S\"))\n)\nnrow(acc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 81735\n```\n\n\n:::\n:::\n\n\n**Gotcha worth flagging:** the first time I read this without specifying `col_types`, `read_csv()` auto-guessed `incident_datetime` as a datetime column already — which sounds convenient, but then calling `lubridate::ymd_hms()` on it (to be safe/explicit) silently failed on 118 rows, because `ymd_hms()` expects a *character* string and readr's auto-parsed `POSIXct` prints with a `UTC` suffix and sometimes drops the time part in its internal string form, which doesn't match the `ymd_hms` pattern. The fix is to pin the column type explicitly at read time as above (`col_datetime(format = \"%Y-%m-%d %H:%M:%S\")`), which then needs no further parsing at all. I only caught this because my BMR/2022 filter count came out 3 rows short of a plain Python/pandas cross-check.\n\n## Filtering to the Bangkok Metropolitan Region, 2022\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbmr_provinces_en <- c(\"Bangkok\", \"Nonthaburi\", \"Pathum Thani\",\n                       \"Samut Prakan\", \"Nakhon Pathom\", \"Samut Sakhon\")\n\nacc_2022 <- acc |> filter(year(incident_datetime) == 2022)\nnrow(acc_2022)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 21032\n```\n\n\n:::\n\n```{.r .cell-code}\nacc_bmr_all <- acc_2022 |> filter(province_en %in% bmr_provinces_en)\nnrow(acc_bmr_all)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3782\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(is.na(acc_bmr_all$latitude))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 189\n```\n\n\n:::\n:::\n\n\n21,032 accidents nationwide in 2022, of which 3,782 are in the six BMR provinces. 189 of those (5%) have no latitude/longitude — I drop them, since a point pattern needs a location for every point:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc_bmr <- acc_bmr_all |> filter(!is.na(latitude), !is.na(longitude))\nnrow(acc_bmr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3593\n```\n\n\n:::\n:::\n\n\n**3,593 geolocated accidents** is the working dataset for the rest of this exercise.\n\n## Converting to `sf`, then to `spatstat`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc_sf <- st_as_sf(acc_bmr, coords = c(\"longitude\", \"latitude\"), crs = 4326) |>\n  st_transform(32647)\n```\n:::\n\n\nA handful of points sit just outside the dissolved BMR polygon (coordinates that round to the coastline/river or a boundary sliver) — `st_filter()` keeps only the ones genuinely inside the window `spatstat` will use:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc_sf <- st_filter(acc_sf, bmr_union)\nnrow(acc_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3590\n```\n\n\n:::\n:::\n\n\n3,590 points make it through. Now the `spatstat` conversion — an `owin` from the polygon, then a `ppp` (planar point pattern) built from the point coordinates against that window:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nowin_bmr <- as.owin(st_geometry(bmr_union))\ncoords <- st_coordinates(acc_sf)\nacc_ppp <- ppp(x = coords[, 1], y = coords[, 2], window = owin_bmr)\nacc_ppp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPlanar point pattern: 3590 points\nwindow: polygonal boundary\nenclosing rectangle: [587130.4, 712441.7] x [1484748.9, 1579087.2] units\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(duplicated(acc_ppp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 321\n```\n\n\n:::\n:::\n\n\n**321 exact duplicate coordinates** — different accidents recorded at the same lat/long to several decimal places, most likely because the source data snapped each report to the nearest intersection or km-marker rather than a precise GPS fix. Exact duplicates aren't a problem for KDE, but they *are* a problem for nearest-neighbour statistics (the G function in particular), where a distance of exactly zero between two \"different\" points is a degenerate case rather than a genuine measurement. The standard fix is `rjitter()` — nudge every point by a small random offset (I used a 5 m radius, well below anything meaningful at BMR scale) to break exact ties without disturbing the actual spatial pattern:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(415)\nacc_ppp <- rjitter(acc_ppp, retry = TRUE, nsim = 1, radius = 5)\nsum(duplicated(acc_ppp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\nI'll reuse this jittered `acc_ppp` (and the same jittering logic for every subset built later) throughout the rest of the document.\n\n---\n\n# Exploratory Data Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc_sf |>\n  st_drop_geometry() |>\n  count(province_en, sort = TRUE) |>\n  mutate(pct = round(100 * n / sum(n), 1)) |>\n  kable(col.names = c(\"Province\", \"Accidents\", \"% of total\"),\n        caption = \"2022 BMR accidents by province\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 2022 BMR accidents by province\n\n|Province      | Accidents| % of total|\n|:-------------|---------:|----------:|\n|Bangkok       |      1801|       50.2|\n|Samut Prakan  |       669|       18.6|\n|Pathum Thani  |       486|       13.5|\n|Samut Sakhon  |       324|        9.0|\n|Nonthaburi    |       175|        4.9|\n|Nakhon Pathom |       135|        3.8|\n\n\n:::\n:::\n\n\nBangkok alone accounts for half of all BMR accidents, unsurprising given it's the urban core with by far the densest road network and traffic volume; the outer provinces trail off roughly with distance from the centre. Over the whole sample, these accidents recorded **176 fatalities and 2,093 injuries**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_sf(data = bmr, fill = \"grey97\", colour = \"grey70\") +\n  geom_sf(data = acc_sf, aes(colour = province_en), size = 0.4, alpha = 0.5) +\n  labs(colour = \"Province\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Every geolocated 2022 accident in the BMR, coloured by province.](index_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nEven at this raw-point stage the pattern is obviously not random — points trace out the road network rather than filling space evenly, which is exactly what the first-order and second-order analyses below go on to quantify.\n\n---\n\n# First-Order Spatial Point Pattern Analysis (KDE)\n\nFirst-order analysis asks: **where is accident intensity highest?** Kernel density estimation smooths the discrete point pattern into a continuous surface, so instead of 3,590 dots I get a map of \"accidents per unit area\" that's readable at a glance.\n\n## Choosing a bandwidth\n\nThe bandwidth (`sigma`) controls how much smoothing happens — too small and the map is just noisy dots with a blur radius, too large and every genuine hotspot gets washed into one diffuse blob. `spatstat` offers a few automatic selectors; I checked more than one because of the duplicate-point issue above:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw.diggle(acc_ppp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  sigma \n69.2306 \n```\n\n\n:::\n\n```{.r .cell-code}\nbw.ppl(acc_ppp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  sigma \n786.232 \n```\n\n\n:::\n:::\n\n\n`bw.diggle()` — usually a solid default — comes back at essentially **23 metres**, which is far too small to be useful over an area the size of the BMR. That's the duplicate/near-duplicate points again: `bw.diggle()` is tuned by minimising a criterion sensitive to the very shortest inter-point distances, so a cluster of points sitting almost on top of each other drags it toward zero. `bw.ppl()` — Baddeley's likelihood cross-validation selector, generally recommended over `bw.diggle()` specifically *when the pattern is clustered* (Baddeley, Rubak & Turner, *Spatial Point Patterns*, 2015) — comes back at a much more sensible **~750 m**, and gives the same answer whether duplicates are jittered out first or not. I used `bw.ppl()` throughout.\n\n## Fixed-bandwidth KDE\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_bmr <- density(acc_ppp, sigma = bw.ppl(acc_ppp), edge = TRUE)\nplot(kde_bmr, main = \"\")\n```\n\n::: {.cell-output-display}\n![Fixed-bandwidth KDE of 2022 BMR accidents (bw.ppl ≈ 750 m). Brighter = higher accident intensity.](index_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n## Adaptive KDE\n\nFixed-bandwidth KDE uses the same smoothing radius everywhere, which can over-smooth dense urban clusters and under-smooth the sparser outskirts at the same time. Adaptive KDE lets the bandwidth shrink in dense areas and grow in sparse ones:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_adaptive <- adaptive.density(acc_ppp, method = \"kernel\")\nplot(kde_adaptive, main = \"\")\n```\n\n::: {.cell-output-display}\n![Adaptive KDE of 2022 BMR accidents.](index_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n## Interpretation\n\nBoth surfaces tell the same basic story, which is reassuring: accident intensity is not spread evenly across the BMR, it traces the expressway/arterial road network, with a small number of sharp point hotspots sitting at major interchanges in central-eastern Bangkok. The adaptive version sharpens those interchange hotspots further (since local point density there pulls its effective bandwidth down), while smoothing the low-density fringe more aggressively than the fixed version does. Neither surface shows any hotspot away from a road corridor, which is a reasonable sanity check — accidents can only happen where vehicles are.\n\n---\n\n# Second-Order Spatial Point Pattern Analysis (CSR Testing)\n\nFirst-order analysis shows *where* intensity is high, but it doesn't prove the clustering is statistically real rather than a chance arrangement of otherwise-random points. Second-order analysis tests this directly: compare the observed pattern's G, F, K and L functions against what complete spatial randomness (CSR — points scattered independently at random, i.e. a homogeneous Poisson process) would produce, using Monte Carlo simulation envelopes.\n\nFor all four functions I use `nsim = 99` simulated CSR patterns, which gives a 1/(99+1) = **1% two-sided significance level** for the envelope test — the standard convention.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(415)\nG_env <- envelope(acc_ppp, Gest, nsim = 99, verbose = FALSE)\nF_env <- envelope(acc_ppp, Fest, nsim = 99, verbose = FALSE)\nK_env <- envelope(acc_ppp, Kest, correction = \"border\", nsim = 99, verbose = FALSE)\nL_env <- envelope(acc_ppp, Lest, correction = \"border\", nsim = 99, verbose = FALSE)\n```\n:::\n\n\nI fixed `correction = \"border\"` for `Kest`/`Lest` explicitly — `spatstat`'s default edge-correction choice (isotropic) is far more expensive to compute on a polygon window this irregular (the BMR outline has 300+ vertices) and, with `nsim = 99` simulations to run, the isotropic version didn't finish in a reasonable time. Border correction is simpler (it just discards the area near the window edge rather than reweighting it) but is a standard, valid choice and doesn't change the CSR conclusion here.\n\n## G function — nearest-neighbour distances\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(G_env, main = \"\")\n```\n\n::: {.cell-output-display}\n![G function envelope. Observed (black) above the grey CSR envelope means points have closer neighbours than CSR would predict — i.e. clustering.](index_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n## F function — empty-space function\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(F_env, main = \"\")\n```\n\n::: {.cell-output-display}\n![F function envelope. Observed (black) below the grey CSR envelope also indicates clustering (empty space is easier to find than under CSR, because points are clumped together, leaving larger gaps).](index_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n## K function — Ripley's K\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(K_env, main = \"\")\n```\n\n::: {.cell-output-display}\n![K function envelope. Observed (black) above the CSR envelope across all tested radii indicates clustering at every scale examined.](index_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n## L function — variance-stabilised K\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(L_env, . - r ~ r, main = \"\")\n```\n\n::: {.cell-output-display}\n![L function envelope, plotted as L(r) − r so CSR is a flat line at 0. The observed curve sits far above the envelope at every radius.](index_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n## Clark-Evans test\n\nAs a single-number companion to the four envelope plots, the Clark-Evans index compares the mean observed nearest-neighbour distance to the value expected under CSR: R = 1 means CSR, R < 1 means clustering, R > 1 means regularity/dispersion.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclarkevans.test(acc_ppp, correction = \"cdf\", alternative = \"clustered\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tCDF correction\n\tZ-test\n\ndata:  acc_ppp\nR = 0.21546, p-value < 2.2e-16\nalternative hypothesis: clustered (R < 1)\n```\n\n\n:::\n:::\n\n\n## Interpretation\n\nAll four functions agree, and agree with the KDE maps: the observed curve sits **outside** the simulation envelope in the clustered direction across essentially the whole range tested (G above, F below, K/L above), and the Clark-Evans R statistic of **0.215** — far below 1, p < 2.2 × 10⁻¹⁶ — rejects CSR at any reasonable significance level. In plain terms: 2022 BMR road accidents cluster far more tightly than random chance would produce, and they do so from the very shortest inter-point distances (G function departs from CSR almost immediately) out to the largest radii tested (K/L keep diverging rather than flattening back toward the envelope). That's consistent with a real underlying cause — accidents are physically constrained to the road network, and further concentrated at high-conflict points like busy intersections — rather than any artefact of the analysis.\n\n---\n\n# Spatio-Temporal Analysis\n\nEx03's toolkit stops at \"is this one point pattern clustered.\" The accident data lets me go further: does *where* accidents cluster change depending on *when* they happen? `incident_datetime` gives a continuous time value per point, not just a category, so before cutting it into discrete bins (day/night, weekday/weekend) I first use the technique built for exactly this — spatio-temporal KDE.\n\n## Deriving time attributes\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc_sf <- acc_sf |>\n  mutate(\n    hour = hour(incident_datetime),\n    hour_of_day = hour(incident_datetime) + minute(incident_datetime) / 60,\n    month_num = month(incident_datetime),\n    wday_num = wday(incident_datetime, week_start = 1),\n    period = if_else(hour >= 6 & hour < 18, \"Day\", \"Night\"),\n    daytype = if_else(wday_num <= 5, \"Weekday\", \"Weekend\")\n  )\n\nacc_sf |> st_drop_geometry() |> count(period)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  period     n\n  <chr>  <int>\n1 Day     1938\n2 Night   1652\n```\n\n\n:::\n\n```{.r .cell-code}\nacc_sf |> st_drop_geometry() |> count(daytype)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  daytype     n\n  <chr>   <int>\n1 Weekday  2549\n2 Weekend  1041\n```\n\n\n:::\n:::\n\n\n`hour_of_day` (0–24, continuous) and `month_num` (1–12) feed the STKDE below; `period`/`daytype` are the discrete bins used further down for the formal Monte Carlo test. \"Day\" is 06:00–17:59 and \"Night\" is 18:00–05:59 — a plain 12h/12h split rather than anything tied to actual sunrise/sunset, a simplification worth naming but reasonable at Bangkok's latitude where day length barely varies across the year.\n\n## Spatio-temporal KDE (STKDE)\n\nThis follows [Chapter 6](https://r4gdsa.netlify.app/chap06) of the course's R4GDSA reference directly — that chapter runs `sparr::spattemp.density()` on forest-fire points with month/day-of-year as the time mark; the same recipe applies here with accident points and hour-of-day/month as the marks. The trick is `as.ppp()` on an `sf` object with exactly one numeric column selected: that column becomes the point pattern's **mark**, and `spattemp.density()` reads it as the time dimension, producing a smooth density surface over *(x, y, t)* jointly rather than one KDE per discrete bin.\n\n### By hour of day\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc_hour_ppp <- acc_sf |> select(hour_of_day) |> as.ppp()\nacc_hour_owin <- acc_hour_ppp[owin_bmr]\n\nstkde_hour <- spattemp.density(acc_hour_owin)\nsummary(stkde_hour)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 4882.307 (spatial)\n  lambda = 0.6049 (temporal)\n\nNo. of observations\n  3590 \n\nSpatial bound\n  Type: polygonal\n  2D enclosure: [587130.4, 712441.7] x [1484749, 1579087]\n\nTemporal bound\n  [0, 24]\n\nEvaluation\n  128 x 128 x 25 trivariate lattice\n  Density range: [4.269527e-19, 5.665265e-11]\n```\n\n\n:::\n:::\n\n\n`spattemp.density()` picks its own bandwidths by cross-validation — a spatial one (here ≈ 4,880 m) and a temporal one (here ≈ 0.6 hours) — so I'm not hand-tuning `sigma` the way I did for the plain KDE earlier.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntims <- c(0, 4, 8, 12, 16, 20)\npar(mfcol = c(2, 3))\nfor (i in tims) {\n  plot(stkde_hour, i, override.par = FALSE, fix.range = TRUE,\n       main = paste0(\"Hour \", i))\n}\n```\n\n::: {.cell-output-display}\n![Spatio-temporal KDE sliced at six hours across the day. Same colour scale throughout (fix.range = TRUE).](index_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\nThe hotspot doesn't just dim and brighten in place — it visibly *moves*. Overnight (hour 0–4) it's a single tight, isolated peak; by the morning commute (hour 8) it stretches into a corridor with several near-equal sub-peaks; by midday (hour 12) intensity concentrates sharply back into one dominant peak, now shifted slightly from the overnight location; by evening (hour 16–20) it broadens out again into multiple simultaneous hotspots. A single \"the\" hotspot from the first-order KDE earlier is really an average over a location that's constantly reshaping through the day.\n\n### By month\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc_month_ppp <- acc_sf |> select(month_num) |> as.ppp()\nacc_month_owin <- acc_month_ppp[owin_bmr]\n\nstkde_month <- spattemp.density(acc_month_owin)\nsummary(stkde_month)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 4882.307 (spatial)\n  lambda = 0.0285 (temporal)\n\nNo. of observations\n  3590 \n\nSpatial bound\n  Type: polygonal\n  2D enclosure: [587130.4, 712441.7] x [1484749, 1579087]\n\nTemporal bound\n  [1, 12]\n\nEvaluation\n  128 x 128 x 12 trivariate lattice\n  Density range: [9.453347e-22, 2.851508e-09]\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntims_m <- c(2, 4, 6, 8, 10, 12)\npar(mfcol = c(2, 3))\nfor (i in tims_m) {\n  plot(stkde_month, i, override.par = FALSE, fix.range = TRUE,\n       main = month.name[i])\n}\n```\n\n::: {.cell-output-display}\n![Spatio-temporal KDE sliced at six months across 2022. Same colour scale throughout.](index_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\nThe clearest signal here is intensity, not location: the dominant hotspot is present all year at roughly the same place, but it sharpens and brightens noticeably from October through December — the same three months that had the highest raw accident counts in the EDA table earlier (394, 367, 369 respectively). Year-end isn't just busier everywhere; it's busier in a more spatially concentrated way at the existing hotspot rather than spread evenly across the network.\n\n## Discrete time splits: a formal significance test\n\nSTKDE is the right tool for *seeing* how the surface moves continuously through time, but it doesn't on its own hand me a p-value for a specific, policy-relevant question like \"is day genuinely different from night.\" For that I fall back to discrete bins — the `period`/`daytype` columns from above — compared with `spatstat::segregation.test()`, which does have a significance test built in.\n\n### Building comparable point patterns\n\nTo compare the discrete-bin KDE surfaces fairly, I smooth every subset with the **same bandwidth** — `bw.ppl()` computed on the *full* pattern — rather than letting each subset pick its own (a smaller subset naturally wants a larger bandwidth, which would make \"less smoothed because there happen to be more points here\" look like a real spatial difference when it isn't).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_ppp <- function(sf_subset) {\n  co <- st_coordinates(sf_subset)\n  p <- ppp(co[, 1], co[, 2], window = owin_bmr)\n  rjitter(p, retry = TRUE, nsim = 1, radius = 5)\n}\n\nsigma_shared <- bw.ppl(acc_ppp)\n\nday_ppp   <- make_ppp(acc_sf |> filter(period == \"Day\"))\nnight_ppp <- make_ppp(acc_sf |> filter(period == \"Night\"))\nwd_ppp    <- make_ppp(acc_sf |> filter(daytype == \"Weekday\"))\nwe_ppp    <- make_ppp(acc_sf |> filter(daytype == \"Weekend\"))\n```\n:::\n\n\n### Day vs. night\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_day   <- density(day_ppp, sigma = sigma_shared)\nkde_night <- density(night_ppp, sigma = sigma_shared)\nzmax <- max(kde_day$v, kde_night$v, na.rm = TRUE)\n\npar(mfrow = c(1, 2))\nplot(kde_day,   main = paste0(\"Day (n=\", day_ppp$n, \")\"),   zlim = c(0, zmax))\nplot(kde_night, main = paste0(\"Night (n=\", night_ppp$n, \")\"), zlim = c(0, zmax))\n```\n\n::: {.cell-output-display}\n![KDE of accidents by time of day, same bandwidth and colour scale on both panels.](index_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\nThe daytime surface has one noticeably sharper, brighter hotspot at the main central interchange than the night-time surface does at the same location — daytime accidents concentrate more tightly there, consistent with peak-hour congestion at that specific junction, while night-time accidents are spread a bit more broadly along the corridor.\n\n### Weekday vs. weekend\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_wd <- density(wd_ppp, sigma = sigma_shared)\nkde_we <- density(we_ppp, sigma = sigma_shared)\nzmax2 <- max(kde_wd$v, kde_we$v, na.rm = TRUE)\n\npar(mfrow = c(1, 2))\nplot(kde_wd, main = paste0(\"Weekday (n=\", wd_ppp$n, \")\"), zlim = c(0, zmax2))\nplot(kde_we, main = paste0(\"Weekend (n=\", we_ppp$n, \")\"), zlim = c(0, zmax2))\n```\n\n::: {.cell-output-display}\n![KDE of accidents by day type, same bandwidth and colour scale on both panels.](index_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\nThese two look far more alike than the day/night pair — same corridors light up, same interchange stands out — which by eye suggests weekday and weekend accidents don't really relocate spatially, they just happen at different volumes (2,549 vs. 1,041, matching commuter traffic being a weekday phenomenon).\n\n### Formal test: is the spatial pattern actually different?\n\nEyeballing two KDE panels side by side is suggestive but not a statistical test. `spatstat::segregation.test()` is built for exactly this: given a marked point pattern (here, the mark is the time category), it tests whether the *relative* spatial risk surface between the two marks is significantly non-constant — i.e. whether one category is genuinely more concentrated in some places than the other, beyond what you'd expect if every point's mark were just randomly relabelled.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseg_test <- function(sf_data, mark_col, sigma, nsim = 99, seed = 415) {\n  co <- st_coordinates(sf_data)\n  pm <- ppp(co[, 1], co[, 2], window = owin_bmr, marks = factor(sf_data[[mark_col]]))\n  pm <- rjitter(pm, retry = TRUE, nsim = 1, radius = 5)\n  set.seed(seed)\n  segregation.test(pm, sigma = sigma, nsim = nsim)\n}\n\nseg_period  <- seg_test(acc_sf, \"period\",  sigma = 3000)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nComputing observed value... Done.\nComputing 99 simulated values... 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\nDone.\n```\n\n\n:::\n\n```{.r .cell-code}\nseg_daytype <- seg_test(acc_sf, \"daytype\", sigma = 3000)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nComputing observed value... Done.\nComputing 99 simulated values... 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\nDone.\n```\n\n\n:::\n\n```{.r .cell-code}\nseg_period\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte Carlo test of spatial segregation of types\n\ndata:  pm\nT = 61.451, p-value = 0.01\n```\n\n\n:::\n\n```{.r .cell-code}\nseg_daytype\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte Carlo test of spatial segregation of types\n\ndata:  pm\nT = 26.787, p-value = 0.34\n```\n\n\n:::\n:::\n\n\nI used a larger, fixed `sigma = 3000` m for this test specifically — `segregation.test()` calls `relrisk()` internally to estimate the spatial risk surface, and at the `bw.ppl()` scale (~750 m) that surface underflows to numerically unstable 0/1 values over large stretches of the study area (a `spatstat` warning flags this directly). A larger bandwidth is needed for a *relative-risk* surface to stay numerically well-behaved across an area this size than for a plain density surface — the two are estimating different things even though both use \"sigma.\"\n\n## Interpretation\n\nPutting the continuous STKDE picture and the discrete formal test together, they agree and reinforce each other:\n\n- The **hour-of-day STKDE** shows the hotspot's location and shape genuinely reshaping across the 24-hour cycle, not just dimming and brightening in place — and the discrete test confirms this is statistically real: **day vs. night, p = 0.01**, significant spatial segregation. Where accidents happen genuinely shifts between day and night, not just how many.\n- The **weekday/weekend discrete test gives the opposite answer — p = 0.34**, not significant. Weekday and weekend accidents share essentially the same spatial footprint; only the volume changes (2,549 vs. 1,041). I didn't run a weekday/weekend STKDE for the same reason there's no continuous \"weekday-ness\" variable to feed it — day-of-week is inherently categorical, which is exactly the kind of split discrete testing is built for and STKDE isn't.\n- The **month STKDE** adds a dimension neither of the day-of-week splits could show on its own: the hotspot doesn't relocate across the year, but it does intensify and sharpen from October through December, tracking the same months with the highest raw counts.\n\nThat maps onto a sensible real-world explanation: time-of-day changes *what kind* of driving is happening at a given location (peak-hour congestion at specific junctions vs. free-flowing night traffic), which is a spatial effect; weekday/weekend mostly changes *how much* traffic uses the same road network, a volume effect rather than a spatial one; and year-end changes both — more accidents, concentrated more tightly at the existing hotspot rather than spread out.\n\n---\n\n# Value-Added Analysis: Does Weather Affect Where Accidents Cluster?\n\nThe brief calls out `weather_condition`, `vehicle_type` and `presumed_cause` as optional extra angles. I went with **weather**, because it's the one with the cleanest natural comparison and enough data on both sides to trust the result: of the 3,590 points, 3,263 are logged as `clear` and 309 as `rainy` (the remaining `dark`/`foggy`/`other` categories are too small — 18 points combined — for a meaningful spatial test on their own). `presumed_cause` looked tempting too (alcohol-related accidents in particular), but the largest single non-\"speeding\"/\"other\" category, alcohol, is only 39 points BMR-wide in 2022 — too thin to say anything statistically defensible about its spatial pattern specifically.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc_sf |> st_drop_geometry() |> count(weather_condition, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  weather_condition     n\n  <chr>             <int>\n1 clear              3263\n2 rainy               309\n3 other                15\n4 dark                  2\n5 foggy                 1\n```\n\n\n:::\n:::\n\n\n## KDE by weather condition\n\nUnlike the day/night comparison, I let each weather subset use its **own** `bw.ppl()` bandwidth here rather than sharing one — the two groups differ in size by an order of magnitude (3,263 vs. 309), and forcing the sparser rainy-day pattern through the same tight ~630 m bandwidth tuned for the dense clear-day pattern would just render as a scatter of unconnected dots, telling me nothing about where its own hotspots are.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclear_ppp <- make_ppp(acc_sf |> filter(weather_condition == \"clear\"))\nrainy_ppp <- make_ppp(acc_sf |> filter(weather_condition == \"rainy\"))\n\nsigma_clear <- bw.ppl(clear_ppp)\nsigma_rainy <- bw.ppl(rainy_ppp)\n\nkde_clear <- density(clear_ppp, sigma = sigma_clear)\nkde_rainy <- density(rainy_ppp, sigma = sigma_rainy)\n\npar(mfrow = c(1, 2))\nplot(kde_clear, main = paste0(\"Clear (n=\", clear_ppp$n, \"), σ≈\", round(sigma_clear), \"m\"))\nplot(kde_rainy, main = paste0(\"Rainy (n=\", rainy_ppp$n, \"), σ≈\", round(sigma_rainy), \"m\"))\n```\n\n::: {.cell-output-display}\n![KDE of accidents by weather condition, each panel on its own bandwidth and colour scale (see caveat below).](index_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n\nBecause the two panels use different bandwidths (~630 m vs. ~2,970 m) they aren't directly comparable by eye in the way the day/night pair was — the rainy panel is inherently smoother just from having fewer points to work with. What *is* comparable: clear-weather accidents trace the road network tightly, with the sharpest hotspot at the same central interchange seen throughout this document; rainy-weather accidents, even smoothed over a much wider radius, still concentrate most heavily in the east-central part of the study area rather than spreading evenly across it — a different part of the network than clear-weather's single dominant hotspot.\n\n## Formal test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseg_weather <- seg_test(\n  acc_sf |> filter(weather_condition %in% c(\"clear\", \"rainy\")),\n  \"weather_condition\", sigma = 3000\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nComputing observed value... Done.\nComputing 99 simulated values... 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\nDone.\n```\n\n\n:::\n\n```{.r .cell-code}\nseg_weather\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte Carlo test of spatial segregation of types\n\ndata:  pm\nT = 28.983, p-value = 0.01\n```\n\n\n:::\n:::\n\n\n## Interpretation\n\n`segregation.test()` returns **p = 0.01**, significant at the 5% level: clear-weather and rainy-weather accidents are not just different in volume (3,263 vs. 309, tracking the fact that it isn't raining most of the time) but occupy meaningfully different locations within the BMR. A plausible mechanism: rain doesn't just add slickness uniformly everywhere, it exposes drainage, visibility and road-surface weaknesses that are concentrated in particular stretches of the network — so the \"risky when wet\" locations aren't simply the same \"risky all the time\" locations scaled down. That's a genuinely different, actionable finding from the first-order KDE alone, which only ever showed one dominant hotspot regardless of conditions.\n\n---\n\n# Summary\n\n## Key findings\n\n1. **First-order**: 2022 BMR accidents are heavily concentrated along the expressway/arterial network, with the sharpest hotspot at a central-eastern interchange in Bangkok. Both fixed and adaptive KDE agree on the location.\n2. **Second-order**: G, F, K and L function envelopes, plus a Clark-Evans R of 0.215 (p < 2.2 × 10⁻¹⁶), all confirm the clustering is statistically real and holds from the shortest to the longest spatial scales tested — this is not an artefact of random chance.\n3. **Spatio-temporal**: STKDE (`sparr::spattemp.density()`, Chapter 6's method) shows the hotspot's location and shape reshaping continuously across the 24-hour cycle, and intensifying at the same location from October–December. The discrete formal test confirms day vs. night is a real spatial effect (`segregation.test` p ≈ 0.01) while weekday vs. weekend is not (p ≈ 0.34, volume-only).\n4. **Value-added (weather)**: rainy-weather accidents cluster in a significantly different part of the BMR than clear-weather accidents do (p ≈ 0.01), not just in smaller numbers.\n\n## Limitations\n\n- The BMR boundary is a name-based union of six provinces, not an official metro-area polygon — some edge effects near provincial borders are possible.\n- 5% of BMR 2022 accident records have no coordinates and were dropped; if missingness isn't spatially random (e.g. concentrated in a particular reporting agency or district), the hotspots shown here could be mildly biased.\n- 321 points shared exact duplicate coordinates before jittering, most likely reflecting reporting granularity (nearest landmark/km-marker) rather than true identical locations — jittering fixes the statistical degeneracy but the true precision of any individual point is uncertain.\n- The day/night split (06:00–17:59 vs. 18:00–05:59) is a fixed clock-time boundary, not tied to actual daylight — a reasonable approximation at this latitude but not exact.\n\n## Data sources\n\n- Thailand Road Accident 2019–2022 dataset — [Kaggle](https://www.kaggle.com/datasets/thaweewatboy/thailand-road-accident-2019-2022)\n- Thailand ADM1 province boundaries — [geoBoundaries](https://www.geoboundaries.org/)\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}