<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Andrew Huang">
<meta name="dcterms.date" content="2026-09-09">

<title>Take-home Exercise 1: Spatio-temporal Analysis of Road Traffic Accidents – Huang Kang-Chih | Geospatial</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-6abc373680150e3b257f2be74c2c9465.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Huang Kang-Chih | Geospatial</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html">
 <span class="dropdown-text">Ex01: Geospatial Data Science with R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html">
 <span class="dropdown-text">Ex02: Thematic Mapping &amp; GeoVisualisation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html">
 <span class="dropdown-text">Ex03: Point Pattern Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html">
 <span class="dropdown-text">Ex04: Spatio-Temporal Point Pattern Analysis</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex01/index.html">
 <span class="dropdown-text">Ex01: Thailand Road Accident Spatio-temporal Analysis</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview"><span class="header-section-number">1</span> Overview</a></li>
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link" data-scroll-target="#getting-started"><span class="header-section-number">2</span> Getting Started</a>
  <ul class="collapse">
  <li><a href="#packages-used" id="toc-packages-used" class="nav-link" data-scroll-target="#packages-used"><span class="header-section-number">2.1</span> Packages used</a></li>
  <li><a href="#data-sources" id="toc-data-sources" class="nav-link" data-scroll-target="#data-sources"><span class="header-section-number">2.2</span> Data sources</a></li>
  </ul></li>
  <li><a href="#importing-and-preparing-the-data" id="toc-importing-and-preparing-the-data" class="nav-link" data-scroll-target="#importing-and-preparing-the-data"><span class="header-section-number">3</span> Importing and Preparing the Data</a>
  <ul class="collapse">
  <li><a href="#geospatial-the-bangkok-metropolitan-region-boundary" id="toc-geospatial-the-bangkok-metropolitan-region-boundary" class="nav-link" data-scroll-target="#geospatial-the-bangkok-metropolitan-region-boundary"><span class="header-section-number">3.1</span> Geospatial: the Bangkok Metropolitan Region boundary</a></li>
  <li><a href="#aspatial-the-accident-records" id="toc-aspatial-the-accident-records" class="nav-link" data-scroll-target="#aspatial-the-accident-records"><span class="header-section-number">3.2</span> Aspatial: the accident records</a></li>
  <li><a href="#filtering-to-the-bangkok-metropolitan-region-2022" id="toc-filtering-to-the-bangkok-metropolitan-region-2022" class="nav-link" data-scroll-target="#filtering-to-the-bangkok-metropolitan-region-2022"><span class="header-section-number">3.3</span> Filtering to the Bangkok Metropolitan Region, 2022</a></li>
  <li><a href="#converting-to-sf-then-to-spatstat" id="toc-converting-to-sf-then-to-spatstat" class="nav-link" data-scroll-target="#converting-to-sf-then-to-spatstat"><span class="header-section-number">3.4</span> Converting to <code>sf</code>, then to <code>spatstat</code></a></li>
  </ul></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis"><span class="header-section-number">4</span> Exploratory Data Analysis</a></li>
  <li><a href="#first-order-spatial-point-pattern-analysis-kde" id="toc-first-order-spatial-point-pattern-analysis-kde" class="nav-link" data-scroll-target="#first-order-spatial-point-pattern-analysis-kde"><span class="header-section-number">5</span> First-Order Spatial Point Pattern Analysis (KDE)</a>
  <ul class="collapse">
  <li><a href="#choosing-a-bandwidth" id="toc-choosing-a-bandwidth" class="nav-link" data-scroll-target="#choosing-a-bandwidth"><span class="header-section-number">5.1</span> Choosing a bandwidth</a></li>
  <li><a href="#fixed-bandwidth-kde" id="toc-fixed-bandwidth-kde" class="nav-link" data-scroll-target="#fixed-bandwidth-kde"><span class="header-section-number">5.2</span> Fixed-bandwidth KDE</a></li>
  <li><a href="#adaptive-kde" id="toc-adaptive-kde" class="nav-link" data-scroll-target="#adaptive-kde"><span class="header-section-number">5.3</span> Adaptive KDE</a></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation"><span class="header-section-number">5.4</span> Interpretation</a></li>
  </ul></li>
  <li><a href="#second-order-spatial-point-pattern-analysis-csr-testing" id="toc-second-order-spatial-point-pattern-analysis-csr-testing" class="nav-link" data-scroll-target="#second-order-spatial-point-pattern-analysis-csr-testing"><span class="header-section-number">6</span> Second-Order Spatial Point Pattern Analysis (CSR Testing)</a>
  <ul class="collapse">
  <li><a href="#g-function-nearest-neighbour-distances" id="toc-g-function-nearest-neighbour-distances" class="nav-link" data-scroll-target="#g-function-nearest-neighbour-distances"><span class="header-section-number">6.1</span> G function — nearest-neighbour distances</a></li>
  <li><a href="#f-function-empty-space-function" id="toc-f-function-empty-space-function" class="nav-link" data-scroll-target="#f-function-empty-space-function"><span class="header-section-number">6.2</span> F function — empty-space function</a></li>
  <li><a href="#k-function-ripleys-k" id="toc-k-function-ripleys-k" class="nav-link" data-scroll-target="#k-function-ripleys-k"><span class="header-section-number">6.3</span> K function — Ripley’s K</a></li>
  <li><a href="#l-function-variance-stabilised-k" id="toc-l-function-variance-stabilised-k" class="nav-link" data-scroll-target="#l-function-variance-stabilised-k"><span class="header-section-number">6.4</span> L function — variance-stabilised K</a></li>
  <li><a href="#clark-evans-test" id="toc-clark-evans-test" class="nav-link" data-scroll-target="#clark-evans-test"><span class="header-section-number">6.5</span> Clark-Evans test</a></li>
  <li><a href="#interpretation-1" id="toc-interpretation-1" class="nav-link" data-scroll-target="#interpretation-1"><span class="header-section-number">6.6</span> Interpretation</a></li>
  </ul></li>
  <li><a href="#spatio-temporal-analysis" id="toc-spatio-temporal-analysis" class="nav-link" data-scroll-target="#spatio-temporal-analysis"><span class="header-section-number">7</span> Spatio-Temporal Analysis</a>
  <ul class="collapse">
  <li><a href="#deriving-time-attributes" id="toc-deriving-time-attributes" class="nav-link" data-scroll-target="#deriving-time-attributes"><span class="header-section-number">7.1</span> Deriving time attributes</a></li>
  <li><a href="#spatio-temporal-kde-stkde" id="toc-spatio-temporal-kde-stkde" class="nav-link" data-scroll-target="#spatio-temporal-kde-stkde"><span class="header-section-number">7.2</span> Spatio-temporal KDE (STKDE)</a>
  <ul class="collapse">
  <li><a href="#by-hour-of-day" id="toc-by-hour-of-day" class="nav-link" data-scroll-target="#by-hour-of-day"><span class="header-section-number">7.2.1</span> By hour of day</a></li>
  <li><a href="#by-month" id="toc-by-month" class="nav-link" data-scroll-target="#by-month"><span class="header-section-number">7.2.2</span> By month</a></li>
  </ul></li>
  <li><a href="#discrete-time-splits-a-formal-significance-test" id="toc-discrete-time-splits-a-formal-significance-test" class="nav-link" data-scroll-target="#discrete-time-splits-a-formal-significance-test"><span class="header-section-number">7.3</span> Discrete time splits: a formal significance test</a>
  <ul class="collapse">
  <li><a href="#building-comparable-point-patterns" id="toc-building-comparable-point-patterns" class="nav-link" data-scroll-target="#building-comparable-point-patterns"><span class="header-section-number">7.3.1</span> Building comparable point patterns</a></li>
  <li><a href="#day-vs.-night" id="toc-day-vs.-night" class="nav-link" data-scroll-target="#day-vs.-night"><span class="header-section-number">7.3.2</span> Day vs.&nbsp;night</a></li>
  <li><a href="#weekday-vs.-weekend" id="toc-weekday-vs.-weekend" class="nav-link" data-scroll-target="#weekday-vs.-weekend"><span class="header-section-number">7.3.3</span> Weekday vs.&nbsp;weekend</a></li>
  <li><a href="#formal-test-is-the-spatial-pattern-actually-different" id="toc-formal-test-is-the-spatial-pattern-actually-different" class="nav-link" data-scroll-target="#formal-test-is-the-spatial-pattern-actually-different"><span class="header-section-number">7.3.4</span> Formal test: is the spatial pattern actually different?</a></li>
  </ul></li>
  <li><a href="#interpretation-2" id="toc-interpretation-2" class="nav-link" data-scroll-target="#interpretation-2"><span class="header-section-number">7.4</span> Interpretation</a></li>
  </ul></li>
  <li><a href="#value-added-analysis-does-weather-affect-where-accidents-cluster" id="toc-value-added-analysis-does-weather-affect-where-accidents-cluster" class="nav-link" data-scroll-target="#value-added-analysis-does-weather-affect-where-accidents-cluster"><span class="header-section-number">8</span> Value-Added Analysis: Does Weather Affect Where Accidents Cluster?</a>
  <ul class="collapse">
  <li><a href="#kde-by-weather-condition" id="toc-kde-by-weather-condition" class="nav-link" data-scroll-target="#kde-by-weather-condition"><span class="header-section-number">8.1</span> KDE by weather condition</a></li>
  <li><a href="#formal-test" id="toc-formal-test" class="nav-link" data-scroll-target="#formal-test"><span class="header-section-number">8.2</span> Formal test</a></li>
  <li><a href="#interpretation-3" id="toc-interpretation-3" class="nav-link" data-scroll-target="#interpretation-3"><span class="header-section-number">8.3</span> Interpretation</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">9</span> Summary</a>
  <ul class="collapse">
  <li><a href="#key-findings" id="toc-key-findings" class="nav-link" data-scroll-target="#key-findings"><span class="header-section-number">9.1</span> Key findings</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">9.2</span> Limitations</a></li>
  <li><a href="#data-sources-1" id="toc-data-sources-1" class="nav-link" data-scroll-target="#data-sources-1"><span class="header-section-number">9.3</span> Data sources</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-home Exercise 1: Spatio-temporal Analysis of Road Traffic Accidents</h1>
<p class="subtitle lead">First-order and second-order spatial point pattern analysis of 2022 accidents in the Bangkok Metropolitan Region</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Andrew Huang </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 9, 2026</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">September 12, 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="overview" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Overview</h1>
<p>Hands-on Exercise 3 covered spatial point pattern analysis (KDE, Clark-Evans, G/F/K/L functions) on a single static point set. This take-home exercise reuses that whole toolkit on a real dataset — road traffic accidents in Thailand — but adds a dimension Ex03 didn’t touch: <strong>time</strong>. The dataset carries a full timestamp per accident (<code>incident_datetime</code>), so on top of “where do accidents cluster” I can also ask “does <em>where</em> they cluster change depending on <em>when</em>” — day vs.&nbsp;night, weekday vs.&nbsp;weekend.</p>
<p>The brief has three required parts plus one open-ended one:</p>
<ol type="1">
<li><strong>First-order analysis</strong> — kernel density estimation (KDE) to map accident hotspots across the study area.</li>
<li><strong>Second-order analysis</strong> — G, F, K and L functions with Monte Carlo envelopes to test whether the clustering is statistically real (i.e.&nbsp;not what we’d expect under complete spatial randomness, CSR).</li>
<li><strong>Spatio-temporal analysis</strong> — the dedicated technique here is spatio-temporal KDE (STKDE) via the <code>sparr</code> package, the method taught in <a href="https://r4gdsa.netlify.app/chap06">Chapter 6 of the course’s R4GDSA reference</a> (that chapter demonstrates it on Indonesian forest-fire data; here it’s applied to accidents). On top of that I also split the pattern into discrete time periods (day/night, weekday/weekend) and run a formal Monte Carlo test for whether the spatial pattern itself differs across those splits.</li>
<li><strong>Value-added analysis</strong> — my own extension, using one of the extra attribute columns the dataset provides (<code>weather_condition</code>, <code>vehicle_type</code>, <code>presumed_cause</code>) to dig one level deeper.</li>
</ol>
<p><strong>Study area and scope.</strong> The raw CSV covers the whole of Thailand from 2019–2022. The assignment only asks for the <strong>Bangkok Metropolitan Region (BMR)</strong> — Bangkok plus the five surrounding provinces (Nonthaburi, Pathum Thani, Samut Prakan, Nakhon Pathom, Samut Sakhon) that are conventionally grouped with it — restricted to <strong>2022</strong>. Filtering down to that scope is the first thing the data-preparation section below does.</p>
<hr>
</section>
<section id="getting-started" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Getting Started</h1>
<section id="packages-used" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="packages-used"><span class="header-section-number">2.1</span> Packages used</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, spatstat, sparr, tidyverse, lubridate, knitr, kableExtra)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><strong>sf</strong>: reading/writing vector geospatial data and all the geometric operations (projection, filtering, union).</li>
<li><strong>spatstat</strong>: everything point-pattern — <code>ppp</code>, <code>owin</code>, <code>density()</code>, <code>envelope()</code>, <code>Gest</code>/<code>Fest</code>/<code>Kest</code>/<code>Lest</code>, <code>clarkevans.test()</code>, <code>segregation.test()</code>. This is the same package Ex03 used.</li>
<li><strong>sparr</strong>: <code>spattemp.density()</code> — spatio-temporal kernel density estimation, the technique from Chapter 6.</li>
<li><strong>tidyverse</strong> / <strong>lubridate</strong>: data wrangling and date-time handling.</li>
<li><strong>knitr</strong> / <strong>kableExtra</strong>: tidy tables.</li>
</ul>
<p>Unlike Ex01/Ex02 I’m not loading <code>tmap</code> here — KDE surfaces and the G/F/K/L plots are <code>spatstat</code> objects (<code>im</code>, <code>fv</code>), and <code>spatstat</code>’s own <code>plot()</code> methods are the standard way to look at them (that’s also what the lecture slides do). <code>ggplot2</code> + <code>sf</code> covers the handful of ordinary vector maps/charts I need elsewhere in this document.</p>
</section>
<section id="data-sources" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="data-sources"><span class="header-section-number">2.2</span> Data sources</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Dataset</th>
<th>Type</th>
<th>Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>thai_road_accident_2019_2022.csv</code></td>
<td>Aspatial (point coordinates as columns)</td>
<td><a href="https://www.kaggle.com/datasets/thaweewatboy/thailand-road-accident-2019-2022">Kaggle: Thailand Road Accident 2019–2022</a></td>
</tr>
<tr class="even">
<td>Thailand ADM1 (province) boundaries</td>
<td>Geospatial (polygon)</td>
<td><a href="https://www.geoboundaries.org/">geoBoundaries</a> — <code>geoBoundaries-THA-ADM1</code></td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">list.files</span>(<span class="st">"data/geospatial"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "tha_adm1.geojson"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">list.files</span>(<span class="st">"data/aspatial"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "thai_road_accident_2019_2022.csv"    "thai_road_accident_2019_2022.csv.gz"</code></pre>
</div>
</div>
<hr>
</section>
</section>
<section id="importing-and-preparing-the-data" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Importing and Preparing the Data</h1>
<section id="geospatial-the-bangkok-metropolitan-region-boundary" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="geospatial-the-bangkok-metropolitan-region-boundary"><span class="header-section-number">3.1</span> Geospatial: the Bangkok Metropolitan Region boundary</h2>
<p>The accident CSV has no polygon layer of its own — it’s just latitude/longitude per row — so I need an administrative boundary from elsewhere to (a) define the BMR study area and clip out-of-scope points, and (b) give <code>spatstat</code> an observation window (<code>owin</code>) to compute intensity and edge corrections against. I used geoBoundaries’ Thailand province-level (ADM1) layer.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>adm1 <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"data/geospatial/tha_adm1.geojson"</span>, <span class="at">quiet =</span> <span class="cn">TRUE</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(adm1)<span class="sc">$</span>input</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "WGS 84"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(adm1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 77</code></pre>
</div>
</div>
<p>77 provinces nationwide, in WGS84 (EPSG:4326). BMR isn’t an official administrative unit in this file — it’s Bangkok plus five neighbouring provinces that get treated as one metro area by convention — so I filter by name:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>bmr_names <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Bangkok"</span>, <span class="st">"Nonthaburi Province"</span>, <span class="st">"Pathum Thani Province"</span>,</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Samut Prakan Province"</span>, <span class="st">"Nakhon Pathom Province"</span>, <span class="st">"Samut Sakhon Province"</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>bmr <span class="ot">&lt;-</span> adm1 <span class="sc">|&gt;</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(shapeName <span class="sc">%in%</span> bmr_names) <span class="sc">|&gt;</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="dv">32647</span>)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(bmr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6</code></pre>
</div>
</div>
<p><code>EPSG:32647</code> is WGS 84 / UTM zone 47N, which covers central Thailand including Bangkok — a projected CRS with metre units, needed for any distance-based calculation (KDE bandwidths, K-function radii, etc.) later on. Working in degrees would silently distort every one of those.</p>
<p>I also build a single dissolved polygon (<code>bmr_union</code>) — the six provinces merged into one shape with the internal borders removed. This is what becomes the <code>spatstat</code> observation window; point-pattern statistics don’t care about which province a point falls in, only whether it falls inside <em>the</em> window.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>bmr_union <span class="ot">&lt;-</span> <span class="fu">st_union</span>(bmr) <span class="sc">|&gt;</span> <span class="fu">st_sf</span>() <span class="sc">|&gt;</span> <span class="fu">st_make_valid</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> bmr, <span class="fu">aes</span>(<span class="at">fill =</span> shapeName), <span class="at">colour =</span> <span class="st">"white"</span>, <span class="at">linewidth =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> bmr_union, <span class="at">fill =</span> <span class="cn">NA</span>, <span class="at">colour =</span> <span class="st">"black"</span>, <span class="at">linewidth =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">"Province"</span>) <span class="sc">+</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>The Bangkok Metropolitan Region boundary used as the study area (six provinces dissolved into one polygon).</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="aspatial-the-accident-records" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="aspatial-the-accident-records"><span class="header-section-number">3.2</span> Aspatial: the accident records</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>acc <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"data/aspatial/thai_road_accident_2019_2022.csv"</span>,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">show_col_types =</span> <span class="cn">FALSE</span>,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">col_types =</span> <span class="fu">cols</span>(<span class="at">incident_datetime =</span> <span class="fu">col_datetime</span>(<span class="at">format =</span> <span class="st">"%Y-%m-%d %H:%M:%S"</span>))</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(acc)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 81735</code></pre>
</div>
</div>
<p><strong>Gotcha worth flagging:</strong> the first time I read this without specifying <code>col_types</code>, <code>read_csv()</code> auto-guessed <code>incident_datetime</code> as a datetime column already — which sounds convenient, but then calling <code>lubridate::ymd_hms()</code> on it (to be safe/explicit) silently failed on 118 rows, because <code>ymd_hms()</code> expects a <em>character</em> string and readr’s auto-parsed <code>POSIXct</code> prints with a <code>UTC</code> suffix and sometimes drops the time part in its internal string form, which doesn’t match the <code>ymd_hms</code> pattern. The fix is to pin the column type explicitly at read time as above (<code>col_datetime(format = "%Y-%m-%d %H:%M:%S")</code>), which then needs no further parsing at all. I only caught this because my BMR/2022 filter count came out 3 rows short of a plain Python/pandas cross-check.</p>
</section>
<section id="filtering-to-the-bangkok-metropolitan-region-2022" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="filtering-to-the-bangkok-metropolitan-region-2022"><span class="header-section-number">3.3</span> Filtering to the Bangkok Metropolitan Region, 2022</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>bmr_provinces_en <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Bangkok"</span>, <span class="st">"Nonthaburi"</span>, <span class="st">"Pathum Thani"</span>,</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"Samut Prakan"</span>, <span class="st">"Nakhon Pathom"</span>, <span class="st">"Samut Sakhon"</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>acc_2022 <span class="ot">&lt;-</span> acc <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="fu">year</span>(incident_datetime) <span class="sc">==</span> <span class="dv">2022</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(acc_2022)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21032</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>acc_bmr_all <span class="ot">&lt;-</span> acc_2022 <span class="sc">|&gt;</span> <span class="fu">filter</span>(province_en <span class="sc">%in%</span> bmr_provinces_en)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(acc_bmr_all)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3782</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(acc_bmr_all<span class="sc">$</span>latitude))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 189</code></pre>
</div>
</div>
<p>21,032 accidents nationwide in 2022, of which 3,782 are in the six BMR provinces. 189 of those (5%) have no latitude/longitude — I drop them, since a point pattern needs a location for every point:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>acc_bmr <span class="ot">&lt;-</span> acc_bmr_all <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(latitude), <span class="sc">!</span><span class="fu">is.na</span>(longitude))</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(acc_bmr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3593</code></pre>
</div>
</div>
<p><strong>3,593 geolocated accidents</strong> is the working dataset for the rest of this exercise.</p>
</section>
<section id="converting-to-sf-then-to-spatstat" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="converting-to-sf-then-to-spatstat"><span class="header-section-number">3.4</span> Converting to <code>sf</code>, then to <code>spatstat</code></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>acc_sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(acc_bmr, <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"longitude"</span>, <span class="st">"latitude"</span>), <span class="at">crs =</span> <span class="dv">4326</span>) <span class="sc">|&gt;</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="dv">32647</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>A handful of points sit just outside the dissolved BMR polygon (coordinates that round to the coastline/river or a boundary sliver) — <code>st_filter()</code> keeps only the ones genuinely inside the window <code>spatstat</code> will use:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>acc_sf <span class="ot">&lt;-</span> <span class="fu">st_filter</span>(acc_sf, bmr_union)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(acc_sf)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3590</code></pre>
</div>
</div>
<p>3,590 points make it through. Now the <code>spatstat</code> conversion — an <code>owin</code> from the polygon, then a <code>ppp</code> (planar point pattern) built from the point coordinates against that window:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>owin_bmr <span class="ot">&lt;-</span> <span class="fu">as.owin</span>(<span class="fu">st_geometry</span>(bmr_union))</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(acc_sf)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>acc_ppp <span class="ot">&lt;-</span> <span class="fu">ppp</span>(<span class="at">x =</span> coords[, <span class="dv">1</span>], <span class="at">y =</span> coords[, <span class="dv">2</span>], <span class="at">window =</span> owin_bmr)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>acc_ppp</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Planar point pattern: 3590 points
window: polygonal boundary
enclosing rectangle: [587130.4, 712441.7] x [1484748.9, 1579087.2] units</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">duplicated</span>(acc_ppp))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 321</code></pre>
</div>
</div>
<p><strong>321 exact duplicate coordinates</strong> — different accidents recorded at the same lat/long to several decimal places, most likely because the source data snapped each report to the nearest intersection or km-marker rather than a precise GPS fix. Exact duplicates aren’t a problem for KDE, but they <em>are</em> a problem for nearest-neighbour statistics (the G function in particular), where a distance of exactly zero between two “different” points is a degenerate case rather than a genuine measurement. The standard fix is <code>rjitter()</code> — nudge every point by a small random offset (I used a 5 m radius, well below anything meaningful at BMR scale) to break exact ties without disturbing the actual spatial pattern:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">415</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>acc_ppp <span class="ot">&lt;-</span> <span class="fu">rjitter</span>(acc_ppp, <span class="at">retry =</span> <span class="cn">TRUE</span>, <span class="at">nsim =</span> <span class="dv">1</span>, <span class="at">radius =</span> <span class="dv">5</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">duplicated</span>(acc_ppp))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>I’ll reuse this jittered <code>acc_ppp</code> (and the same jittering logic for every subset built later) throughout the rest of the document.</p>
<hr>
</section>
</section>
<section id="exploratory-data-analysis" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Exploratory Data Analysis</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>acc_sf <span class="sc">|&gt;</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">|&gt;</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(province_en, <span class="at">sort =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct =</span> <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> n <span class="sc">/</span> <span class="fu">sum</span>(n), <span class="dv">1</span>)) <span class="sc">|&gt;</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Province"</span>, <span class="st">"Accidents"</span>, <span class="st">"% of total"</span>),</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">caption =</span> <span class="st">"2022 BMR accidents by province"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>2022 BMR accidents by province</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Province</th>
<th style="text-align: right;">Accidents</th>
<th style="text-align: right;">% of total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Bangkok</td>
<td style="text-align: right;">1801</td>
<td style="text-align: right;">50.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Samut Prakan</td>
<td style="text-align: right;">669</td>
<td style="text-align: right;">18.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pathum Thani</td>
<td style="text-align: right;">486</td>
<td style="text-align: right;">13.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Samut Sakhon</td>
<td style="text-align: right;">324</td>
<td style="text-align: right;">9.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nonthaburi</td>
<td style="text-align: right;">175</td>
<td style="text-align: right;">4.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nakhon Pathom</td>
<td style="text-align: right;">135</td>
<td style="text-align: right;">3.8</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Bangkok alone accounts for half of all BMR accidents, unsurprising given it’s the urban core with by far the densest road network and traffic volume; the outer provinces trail off roughly with distance from the centre. Over the whole sample, these accidents recorded <strong>176 fatalities and 2,093 injuries</strong>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> bmr, <span class="at">fill =</span> <span class="st">"grey97"</span>, <span class="at">colour =</span> <span class="st">"grey70"</span>) <span class="sc">+</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> acc_sf, <span class="fu">aes</span>(<span class="at">colour =</span> province_en), <span class="at">size =</span> <span class="fl">0.4</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">colour =</span> <span class="st">"Province"</span>) <span class="sc">+</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Every geolocated 2022 accident in the BMR, coloured by province.</figcaption>
</figure>
</div>
</div>
</div>
<p>Even at this raw-point stage the pattern is obviously not random — points trace out the road network rather than filling space evenly, which is exactly what the first-order and second-order analyses below go on to quantify.</p>
<hr>
</section>
<section id="first-order-spatial-point-pattern-analysis-kde" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> First-Order Spatial Point Pattern Analysis (KDE)</h1>
<p>First-order analysis asks: <strong>where is accident intensity highest?</strong> Kernel density estimation smooths the discrete point pattern into a continuous surface, so instead of 3,590 dots I get a map of “accidents per unit area” that’s readable at a glance.</p>
<section id="choosing-a-bandwidth" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="choosing-a-bandwidth"><span class="header-section-number">5.1</span> Choosing a bandwidth</h2>
<p>The bandwidth (<code>sigma</code>) controls how much smoothing happens — too small and the map is just noisy dots with a blur radius, too large and every genuine hotspot gets washed into one diffuse blob. <code>spatstat</code> offers a few automatic selectors; I checked more than one because of the duplicate-point issue above:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bw.diggle</span>(acc_ppp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  sigma 
69.2306 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bw.ppl</span>(acc_ppp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  sigma 
786.232 </code></pre>
</div>
</div>
<p><code>bw.diggle()</code> — usually a solid default — comes back at essentially <strong>23 metres</strong>, which is far too small to be useful over an area the size of the BMR. That’s the duplicate/near-duplicate points again: <code>bw.diggle()</code> is tuned by minimising a criterion sensitive to the very shortest inter-point distances, so a cluster of points sitting almost on top of each other drags it toward zero. <code>bw.ppl()</code> — Baddeley’s likelihood cross-validation selector, generally recommended over <code>bw.diggle()</code> specifically <em>when the pattern is clustered</em> (Baddeley, Rubak &amp; Turner, <em>Spatial Point Patterns</em>, 2015) — comes back at a much more sensible <strong>~750 m</strong>, and gives the same answer whether duplicates are jittered out first or not. I used <code>bw.ppl()</code> throughout.</p>
</section>
<section id="fixed-bandwidth-kde" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="fixed-bandwidth-kde"><span class="header-section-number">5.2</span> Fixed-bandwidth KDE</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>kde_bmr <span class="ot">&lt;-</span> <span class="fu">density</span>(acc_ppp, <span class="at">sigma =</span> <span class="fu">bw.ppl</span>(acc_ppp), <span class="at">edge =</span> <span class="cn">TRUE</span>)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_bmr, <span class="at">main =</span> <span class="st">""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Fixed-bandwidth KDE of 2022 BMR accidents (bw.ppl ≈ 750 m). Brighter = higher accident intensity.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="adaptive-kde" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="adaptive-kde"><span class="header-section-number">5.3</span> Adaptive KDE</h2>
<p>Fixed-bandwidth KDE uses the same smoothing radius everywhere, which can over-smooth dense urban clusters and under-smooth the sparser outskirts at the same time. Adaptive KDE lets the bandwidth shrink in dense areas and grow in sparse ones:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>kde_adaptive <span class="ot">&lt;-</span> <span class="fu">adaptive.density</span>(acc_ppp, <span class="at">method =</span> <span class="st">"kernel"</span>)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_adaptive, <span class="at">main =</span> <span class="st">""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Adaptive KDE of 2022 BMR accidents.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="interpretation" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="interpretation"><span class="header-section-number">5.4</span> Interpretation</h2>
<p>Both surfaces tell the same basic story, which is reassuring: accident intensity is not spread evenly across the BMR, it traces the expressway/arterial road network, with a small number of sharp point hotspots sitting at major interchanges in central-eastern Bangkok. The adaptive version sharpens those interchange hotspots further (since local point density there pulls its effective bandwidth down), while smoothing the low-density fringe more aggressively than the fixed version does. Neither surface shows any hotspot away from a road corridor, which is a reasonable sanity check — accidents can only happen where vehicles are.</p>
<hr>
</section>
</section>
<section id="second-order-spatial-point-pattern-analysis-csr-testing" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Second-Order Spatial Point Pattern Analysis (CSR Testing)</h1>
<p>First-order analysis shows <em>where</em> intensity is high, but it doesn’t prove the clustering is statistically real rather than a chance arrangement of otherwise-random points. Second-order analysis tests this directly: compare the observed pattern’s G, F, K and L functions against what complete spatial randomness (CSR — points scattered independently at random, i.e.&nbsp;a homogeneous Poisson process) would produce, using Monte Carlo simulation envelopes.</p>
<p>For all four functions I use <code>nsim = 99</code> simulated CSR patterns, which gives a 1/(99+1) = <strong>1% two-sided significance level</strong> for the envelope test — the standard convention.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">415</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>G_env <span class="ot">&lt;-</span> <span class="fu">envelope</span>(acc_ppp, Gest, <span class="at">nsim =</span> <span class="dv">99</span>, <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>F_env <span class="ot">&lt;-</span> <span class="fu">envelope</span>(acc_ppp, Fest, <span class="at">nsim =</span> <span class="dv">99</span>, <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>K_env <span class="ot">&lt;-</span> <span class="fu">envelope</span>(acc_ppp, Kest, <span class="at">correction =</span> <span class="st">"border"</span>, <span class="at">nsim =</span> <span class="dv">99</span>, <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>L_env <span class="ot">&lt;-</span> <span class="fu">envelope</span>(acc_ppp, Lest, <span class="at">correction =</span> <span class="st">"border"</span>, <span class="at">nsim =</span> <span class="dv">99</span>, <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>I fixed <code>correction = "border"</code> for <code>Kest</code>/<code>Lest</code> explicitly — <code>spatstat</code>’s default edge-correction choice (isotropic) is far more expensive to compute on a polygon window this irregular (the BMR outline has 300+ vertices) and, with <code>nsim = 99</code> simulations to run, the isotropic version didn’t finish in a reasonable time. Border correction is simpler (it just discards the area near the window edge rather than reweighting it) but is a standard, valid choice and doesn’t change the CSR conclusion here.</p>
<section id="g-function-nearest-neighbour-distances" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="g-function-nearest-neighbour-distances"><span class="header-section-number">6.1</span> G function — nearest-neighbour distances</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(G_env, <span class="at">main =</span> <span class="st">""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>G function envelope. Observed (black) above the grey CSR envelope means points have closer neighbours than CSR would predict — i.e.&nbsp;clustering.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="f-function-empty-space-function" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="f-function-empty-space-function"><span class="header-section-number">6.2</span> F function — empty-space function</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(F_env, <span class="at">main =</span> <span class="st">""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>F function envelope. Observed (black) below the grey CSR envelope also indicates clustering (empty space is easier to find than under CSR, because points are clumped together, leaving larger gaps).</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="k-function-ripleys-k" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="k-function-ripleys-k"><span class="header-section-number">6.3</span> K function — Ripley’s K</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(K_env, <span class="at">main =</span> <span class="st">""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>K function envelope. Observed (black) above the CSR envelope across all tested radii indicates clustering at every scale examined.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="l-function-variance-stabilised-k" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="l-function-variance-stabilised-k"><span class="header-section-number">6.4</span> L function — variance-stabilised K</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(L_env, . <span class="sc">-</span> r <span class="sc">~</span> r, <span class="at">main =</span> <span class="st">""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>L function envelope, plotted as L(r) − r so CSR is a flat line at 0. The observed curve sits far above the envelope at every radius.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="clark-evans-test" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="clark-evans-test"><span class="header-section-number">6.5</span> Clark-Evans test</h2>
<p>As a single-number companion to the four envelope plots, the Clark-Evans index compares the mean observed nearest-neighbour distance to the value expected under CSR: R = 1 means CSR, R &lt; 1 means clustering, R &gt; 1 means regularity/dispersion.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">clarkevans.test</span>(acc_ppp, <span class="at">correction =</span> <span class="st">"cdf"</span>, <span class="at">alternative =</span> <span class="st">"clustered"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Clark-Evans test
    CDF correction
    Z-test

data:  acc_ppp
R = 0.21546, p-value &lt; 2.2e-16
alternative hypothesis: clustered (R &lt; 1)</code></pre>
</div>
</div>
</section>
<section id="interpretation-1" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="interpretation-1"><span class="header-section-number">6.6</span> Interpretation</h2>
<p>All four functions agree, and agree with the KDE maps: the observed curve sits <strong>outside</strong> the simulation envelope in the clustered direction across essentially the whole range tested (G above, F below, K/L above), and the Clark-Evans R statistic of <strong>0.215</strong> — far below 1, p &lt; 2.2 × 10⁻¹⁶ — rejects CSR at any reasonable significance level. In plain terms: 2022 BMR road accidents cluster far more tightly than random chance would produce, and they do so from the very shortest inter-point distances (G function departs from CSR almost immediately) out to the largest radii tested (K/L keep diverging rather than flattening back toward the envelope). That’s consistent with a real underlying cause — accidents are physically constrained to the road network, and further concentrated at high-conflict points like busy intersections — rather than any artefact of the analysis.</p>
<hr>
</section>
</section>
<section id="spatio-temporal-analysis" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Spatio-Temporal Analysis</h1>
<p>Ex03’s toolkit stops at “is this one point pattern clustered.” The accident data lets me go further: does <em>where</em> accidents cluster change depending on <em>when</em> they happen? <code>incident_datetime</code> gives a continuous time value per point, not just a category, so before cutting it into discrete bins (day/night, weekday/weekend) I first use the technique built for exactly this — spatio-temporal KDE.</p>
<section id="deriving-time-attributes" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="deriving-time-attributes"><span class="header-section-number">7.1</span> Deriving time attributes</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>acc_sf <span class="ot">&lt;-</span> acc_sf <span class="sc">|&gt;</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">hour =</span> <span class="fu">hour</span>(incident_datetime),</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">hour_of_day =</span> <span class="fu">hour</span>(incident_datetime) <span class="sc">+</span> <span class="fu">minute</span>(incident_datetime) <span class="sc">/</span> <span class="dv">60</span>,</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">month_num =</span> <span class="fu">month</span>(incident_datetime),</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">wday_num =</span> <span class="fu">wday</span>(incident_datetime, <span class="at">week_start =</span> <span class="dv">1</span>),</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">period =</span> <span class="fu">if_else</span>(hour <span class="sc">&gt;=</span> <span class="dv">6</span> <span class="sc">&amp;</span> hour <span class="sc">&lt;</span> <span class="dv">18</span>, <span class="st">"Day"</span>, <span class="st">"Night"</span>),</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">daytype =</span> <span class="fu">if_else</span>(wday_num <span class="sc">&lt;=</span> <span class="dv">5</span>, <span class="st">"Weekday"</span>, <span class="st">"Weekend"</span>)</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>acc_sf <span class="sc">|&gt;</span> <span class="fu">st_drop_geometry</span>() <span class="sc">|&gt;</span> <span class="fu">count</span>(period)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  period     n
  &lt;chr&gt;  &lt;int&gt;
1 Day     1938
2 Night   1652</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>acc_sf <span class="sc">|&gt;</span> <span class="fu">st_drop_geometry</span>() <span class="sc">|&gt;</span> <span class="fu">count</span>(daytype)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  daytype     n
  &lt;chr&gt;   &lt;int&gt;
1 Weekday  2549
2 Weekend  1041</code></pre>
</div>
</div>
<p><code>hour_of_day</code> (0–24, continuous) and <code>month_num</code> (1–12) feed the STKDE below; <code>period</code>/<code>daytype</code> are the discrete bins used further down for the formal Monte Carlo test. “Day” is 06:00–17:59 and “Night” is 18:00–05:59 — a plain 12h/12h split rather than anything tied to actual sunrise/sunset, a simplification worth naming but reasonable at Bangkok’s latitude where day length barely varies across the year.</p>
</section>
<section id="spatio-temporal-kde-stkde" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="spatio-temporal-kde-stkde"><span class="header-section-number">7.2</span> Spatio-temporal KDE (STKDE)</h2>
<p>This follows <a href="https://r4gdsa.netlify.app/chap06">Chapter 6</a> of the course’s R4GDSA reference directly — that chapter runs <code>sparr::spattemp.density()</code> on forest-fire points with month/day-of-year as the time mark; the same recipe applies here with accident points and hour-of-day/month as the marks. The trick is <code>as.ppp()</code> on an <code>sf</code> object with exactly one numeric column selected: that column becomes the point pattern’s <strong>mark</strong>, and <code>spattemp.density()</code> reads it as the time dimension, producing a smooth density surface over <em>(x, y, t)</em> jointly rather than one KDE per discrete bin.</p>
<section id="by-hour-of-day" class="level3" data-number="7.2.1">
<h3 data-number="7.2.1" class="anchored" data-anchor-id="by-hour-of-day"><span class="header-section-number">7.2.1</span> By hour of day</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>acc_hour_ppp <span class="ot">&lt;-</span> acc_sf <span class="sc">|&gt;</span> <span class="fu">select</span>(hour_of_day) <span class="sc">|&gt;</span> <span class="fu">as.ppp</span>()</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>acc_hour_owin <span class="ot">&lt;-</span> acc_hour_ppp[owin_bmr]</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>stkde_hour <span class="ot">&lt;-</span> <span class="fu">spattemp.density</span>(acc_hour_owin)</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(stkde_hour)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Spatiotemporal Kernel Density Estimate

Bandwidths
  h = 4882.307 (spatial)
  lambda = 0.6049 (temporal)

No. of observations
  3590 

Spatial bound
  Type: polygonal
  2D enclosure: [587130.4, 712441.7] x [1484749, 1579087]

Temporal bound
  [0, 24]

Evaluation
  128 x 128 x 25 trivariate lattice
  Density range: [4.269527e-19, 5.665265e-11]</code></pre>
</div>
</div>
<p><code>spattemp.density()</code> picks its own bandwidths by cross-validation — a spatial one (here ≈ 4,880 m) and a temporal one (here ≈ 0.6 hours) — so I’m not hand-tuning <code>sigma</code> the way I did for the plain KDE earlier.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>tims <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">4</span>, <span class="dv">8</span>, <span class="dv">12</span>, <span class="dv">16</span>, <span class="dv">20</span>)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfcol =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>))</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> tims) {</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(stkde_hour, i, <span class="at">override.par =</span> <span class="cn">FALSE</span>, <span class="at">fix.range =</span> <span class="cn">TRUE</span>,</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">main =</span> <span class="fu">paste0</span>(<span class="st">"Hour "</span>, i))</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Spatio-temporal KDE sliced at six hours across the day. Same colour scale throughout (fix.range = TRUE).</figcaption>
</figure>
</div>
</div>
</div>
<p>The hotspot doesn’t just dim and brighten in place — it visibly <em>moves</em>. Overnight (hour 0–4) it’s a single tight, isolated peak; by the morning commute (hour 8) it stretches into a corridor with several near-equal sub-peaks; by midday (hour 12) intensity concentrates sharply back into one dominant peak, now shifted slightly from the overnight location; by evening (hour 16–20) it broadens out again into multiple simultaneous hotspots. A single “the” hotspot from the first-order KDE earlier is really an average over a location that’s constantly reshaping through the day.</p>
</section>
<section id="by-month" class="level3" data-number="7.2.2">
<h3 data-number="7.2.2" class="anchored" data-anchor-id="by-month"><span class="header-section-number">7.2.2</span> By month</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>acc_month_ppp <span class="ot">&lt;-</span> acc_sf <span class="sc">|&gt;</span> <span class="fu">select</span>(month_num) <span class="sc">|&gt;</span> <span class="fu">as.ppp</span>()</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>acc_month_owin <span class="ot">&lt;-</span> acc_month_ppp[owin_bmr]</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>stkde_month <span class="ot">&lt;-</span> <span class="fu">spattemp.density</span>(acc_month_owin)</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(stkde_month)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Spatiotemporal Kernel Density Estimate

Bandwidths
  h = 4882.307 (spatial)
  lambda = 0.0285 (temporal)

No. of observations
  3590 

Spatial bound
  Type: polygonal
  2D enclosure: [587130.4, 712441.7] x [1484749, 1579087]

Temporal bound
  [1, 12]

Evaluation
  128 x 128 x 12 trivariate lattice
  Density range: [9.453347e-22, 2.851508e-09]</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>tims_m <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">8</span>, <span class="dv">10</span>, <span class="dv">12</span>)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfcol =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>))</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> tims_m) {</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(stkde_month, i, <span class="at">override.par =</span> <span class="cn">FALSE</span>, <span class="at">fix.range =</span> <span class="cn">TRUE</span>,</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">main =</span> month.name[i])</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Spatio-temporal KDE sliced at six months across 2022. Same colour scale throughout.</figcaption>
</figure>
</div>
</div>
</div>
<p>The clearest signal here is intensity, not location: the dominant hotspot is present all year at roughly the same place, but it sharpens and brightens noticeably from October through December — the same three months that had the highest raw accident counts in the EDA table earlier (394, 367, 369 respectively). Year-end isn’t just busier everywhere; it’s busier in a more spatially concentrated way at the existing hotspot rather than spread evenly across the network.</p>
</section>
</section>
<section id="discrete-time-splits-a-formal-significance-test" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="discrete-time-splits-a-formal-significance-test"><span class="header-section-number">7.3</span> Discrete time splits: a formal significance test</h2>
<p>STKDE is the right tool for <em>seeing</em> how the surface moves continuously through time, but it doesn’t on its own hand me a p-value for a specific, policy-relevant question like “is day genuinely different from night.” For that I fall back to discrete bins — the <code>period</code>/<code>daytype</code> columns from above — compared with <code>spatstat::segregation.test()</code>, which does have a significance test built in.</p>
<section id="building-comparable-point-patterns" class="level3" data-number="7.3.1">
<h3 data-number="7.3.1" class="anchored" data-anchor-id="building-comparable-point-patterns"><span class="header-section-number">7.3.1</span> Building comparable point patterns</h3>
<p>To compare the discrete-bin KDE surfaces fairly, I smooth every subset with the <strong>same bandwidth</strong> — <code>bw.ppl()</code> computed on the <em>full</em> pattern — rather than letting each subset pick its own (a smaller subset naturally wants a larger bandwidth, which would make “less smoothed because there happen to be more points here” look like a real spatial difference when it isn’t).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>make_ppp <span class="ot">&lt;-</span> <span class="cf">function</span>(sf_subset) {</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  co <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(sf_subset)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">ppp</span>(co[, <span class="dv">1</span>], co[, <span class="dv">2</span>], <span class="at">window =</span> owin_bmr)</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rjitter</span>(p, <span class="at">retry =</span> <span class="cn">TRUE</span>, <span class="at">nsim =</span> <span class="dv">1</span>, <span class="at">radius =</span> <span class="dv">5</span>)</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>sigma_shared <span class="ot">&lt;-</span> <span class="fu">bw.ppl</span>(acc_ppp)</span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>day_ppp   <span class="ot">&lt;-</span> <span class="fu">make_ppp</span>(acc_sf <span class="sc">|&gt;</span> <span class="fu">filter</span>(period <span class="sc">==</span> <span class="st">"Day"</span>))</span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>night_ppp <span class="ot">&lt;-</span> <span class="fu">make_ppp</span>(acc_sf <span class="sc">|&gt;</span> <span class="fu">filter</span>(period <span class="sc">==</span> <span class="st">"Night"</span>))</span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a>wd_ppp    <span class="ot">&lt;-</span> <span class="fu">make_ppp</span>(acc_sf <span class="sc">|&gt;</span> <span class="fu">filter</span>(daytype <span class="sc">==</span> <span class="st">"Weekday"</span>))</span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a>we_ppp    <span class="ot">&lt;-</span> <span class="fu">make_ppp</span>(acc_sf <span class="sc">|&gt;</span> <span class="fu">filter</span>(daytype <span class="sc">==</span> <span class="st">"Weekend"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="day-vs.-night" class="level3" data-number="7.3.2">
<h3 data-number="7.3.2" class="anchored" data-anchor-id="day-vs.-night"><span class="header-section-number">7.3.2</span> Day vs.&nbsp;night</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>kde_day   <span class="ot">&lt;-</span> <span class="fu">density</span>(day_ppp, <span class="at">sigma =</span> sigma_shared)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>kde_night <span class="ot">&lt;-</span> <span class="fu">density</span>(night_ppp, <span class="at">sigma =</span> sigma_shared)</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>zmax <span class="ot">&lt;-</span> <span class="fu">max</span>(kde_day<span class="sc">$</span>v, kde_night<span class="sc">$</span>v, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_day,   <span class="at">main =</span> <span class="fu">paste0</span>(<span class="st">"Day (n="</span>, day_ppp<span class="sc">$</span>n, <span class="st">")"</span>),   <span class="at">zlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, zmax))</span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_night, <span class="at">main =</span> <span class="fu">paste0</span>(<span class="st">"Night (n="</span>, night_ppp<span class="sc">$</span>n, <span class="st">")"</span>), <span class="at">zlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, zmax))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>KDE of accidents by time of day, same bandwidth and colour scale on both panels.</figcaption>
</figure>
</div>
</div>
</div>
<p>The daytime surface has one noticeably sharper, brighter hotspot at the main central interchange than the night-time surface does at the same location — daytime accidents concentrate more tightly there, consistent with peak-hour congestion at that specific junction, while night-time accidents are spread a bit more broadly along the corridor.</p>
</section>
<section id="weekday-vs.-weekend" class="level3" data-number="7.3.3">
<h3 data-number="7.3.3" class="anchored" data-anchor-id="weekday-vs.-weekend"><span class="header-section-number">7.3.3</span> Weekday vs.&nbsp;weekend</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>kde_wd <span class="ot">&lt;-</span> <span class="fu">density</span>(wd_ppp, <span class="at">sigma =</span> sigma_shared)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>kde_we <span class="ot">&lt;-</span> <span class="fu">density</span>(we_ppp, <span class="at">sigma =</span> sigma_shared)</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>zmax2 <span class="ot">&lt;-</span> <span class="fu">max</span>(kde_wd<span class="sc">$</span>v, kde_we<span class="sc">$</span>v, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_wd, <span class="at">main =</span> <span class="fu">paste0</span>(<span class="st">"Weekday (n="</span>, wd_ppp<span class="sc">$</span>n, <span class="st">")"</span>), <span class="at">zlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, zmax2))</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_we, <span class="at">main =</span> <span class="fu">paste0</span>(<span class="st">"Weekend (n="</span>, we_ppp<span class="sc">$</span>n, <span class="st">")"</span>), <span class="at">zlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, zmax2))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>KDE of accidents by day type, same bandwidth and colour scale on both panels.</figcaption>
</figure>
</div>
</div>
</div>
<p>These two look far more alike than the day/night pair — same corridors light up, same interchange stands out — which by eye suggests weekday and weekend accidents don’t really relocate spatially, they just happen at different volumes (2,549 vs.&nbsp;1,041, matching commuter traffic being a weekday phenomenon).</p>
</section>
<section id="formal-test-is-the-spatial-pattern-actually-different" class="level3" data-number="7.3.4">
<h3 data-number="7.3.4" class="anchored" data-anchor-id="formal-test-is-the-spatial-pattern-actually-different"><span class="header-section-number">7.3.4</span> Formal test: is the spatial pattern actually different?</h3>
<p>Eyeballing two KDE panels side by side is suggestive but not a statistical test. <code>spatstat::segregation.test()</code> is built for exactly this: given a marked point pattern (here, the mark is the time category), it tests whether the <em>relative</em> spatial risk surface between the two marks is significantly non-constant — i.e.&nbsp;whether one category is genuinely more concentrated in some places than the other, beyond what you’d expect if every point’s mark were just randomly relabelled.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>seg_test <span class="ot">&lt;-</span> <span class="cf">function</span>(sf_data, mark_col, sigma, <span class="at">nsim =</span> <span class="dv">99</span>, <span class="at">seed =</span> <span class="dv">415</span>) {</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  co <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(sf_data)</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  pm <span class="ot">&lt;-</span> <span class="fu">ppp</span>(co[, <span class="dv">1</span>], co[, <span class="dv">2</span>], <span class="at">window =</span> owin_bmr, <span class="at">marks =</span> <span class="fu">factor</span>(sf_data[[mark_col]]))</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  pm <span class="ot">&lt;-</span> <span class="fu">rjitter</span>(pm, <span class="at">retry =</span> <span class="cn">TRUE</span>, <span class="at">nsim =</span> <span class="dv">1</span>, <span class="at">radius =</span> <span class="dv">5</span>)</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set.seed</span>(seed)</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">segregation.test</span>(pm, <span class="at">sigma =</span> sigma, <span class="at">nsim =</span> nsim)</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a>seg_period  <span class="ot">&lt;-</span> <span class="fu">seg_test</span>(acc_sf, <span class="st">"period"</span>,  <span class="at">sigma =</span> <span class="dv">3000</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Computing observed value... Done.
Computing 99 simulated values... 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 
99.
Done.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>seg_daytype <span class="ot">&lt;-</span> <span class="fu">seg_test</span>(acc_sf, <span class="st">"daytype"</span>, <span class="at">sigma =</span> <span class="dv">3000</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Computing observed value... Done.
Computing 99 simulated values... 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 
99.
Done.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>seg_period</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Monte Carlo test of spatial segregation of types

data:  pm
T = 61.451, p-value = 0.01</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>seg_daytype</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Monte Carlo test of spatial segregation of types

data:  pm
T = 26.787, p-value = 0.34</code></pre>
</div>
</div>
<p>I used a larger, fixed <code>sigma = 3000</code> m for this test specifically — <code>segregation.test()</code> calls <code>relrisk()</code> internally to estimate the spatial risk surface, and at the <code>bw.ppl()</code> scale (~750 m) that surface underflows to numerically unstable 0/1 values over large stretches of the study area (a <code>spatstat</code> warning flags this directly). A larger bandwidth is needed for a <em>relative-risk</em> surface to stay numerically well-behaved across an area this size than for a plain density surface — the two are estimating different things even though both use “sigma.”</p>
</section>
</section>
<section id="interpretation-2" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="interpretation-2"><span class="header-section-number">7.4</span> Interpretation</h2>
<p>Putting the continuous STKDE picture and the discrete formal test together, they agree and reinforce each other:</p>
<ul>
<li>The <strong>hour-of-day STKDE</strong> shows the hotspot’s location and shape genuinely reshaping across the 24-hour cycle, not just dimming and brightening in place — and the discrete test confirms this is statistically real: <strong>day vs.&nbsp;night, p = 0.01</strong>, significant spatial segregation. Where accidents happen genuinely shifts between day and night, not just how many.</li>
<li>The <strong>weekday/weekend discrete test gives the opposite answer — p = 0.34</strong>, not significant. Weekday and weekend accidents share essentially the same spatial footprint; only the volume changes (2,549 vs.&nbsp;1,041). I didn’t run a weekday/weekend STKDE for the same reason there’s no continuous “weekday-ness” variable to feed it — day-of-week is inherently categorical, which is exactly the kind of split discrete testing is built for and STKDE isn’t.</li>
<li>The <strong>month STKDE</strong> adds a dimension neither of the day-of-week splits could show on its own: the hotspot doesn’t relocate across the year, but it does intensify and sharpen from October through December, tracking the same months with the highest raw counts.</li>
</ul>
<p>That maps onto a sensible real-world explanation: time-of-day changes <em>what kind</em> of driving is happening at a given location (peak-hour congestion at specific junctions vs.&nbsp;free-flowing night traffic), which is a spatial effect; weekday/weekend mostly changes <em>how much</em> traffic uses the same road network, a volume effect rather than a spatial one; and year-end changes both — more accidents, concentrated more tightly at the existing hotspot rather than spread out.</p>
<hr>
</section>
</section>
<section id="value-added-analysis-does-weather-affect-where-accidents-cluster" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Value-Added Analysis: Does Weather Affect Where Accidents Cluster?</h1>
<p>The brief calls out <code>weather_condition</code>, <code>vehicle_type</code> and <code>presumed_cause</code> as optional extra angles. I went with <strong>weather</strong>, because it’s the one with the cleanest natural comparison and enough data on both sides to trust the result: of the 3,590 points, 3,263 are logged as <code>clear</code> and 309 as <code>rainy</code> (the remaining <code>dark</code>/<code>foggy</code>/<code>other</code> categories are too small — 18 points combined — for a meaningful spatial test on their own). <code>presumed_cause</code> looked tempting too (alcohol-related accidents in particular), but the largest single non-“speeding”/“other” category, alcohol, is only 39 points BMR-wide in 2022 — too thin to say anything statistically defensible about its spatial pattern specifically.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>acc_sf <span class="sc">|&gt;</span> <span class="fu">st_drop_geometry</span>() <span class="sc">|&gt;</span> <span class="fu">count</span>(weather_condition, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  weather_condition     n
  &lt;chr&gt;             &lt;int&gt;
1 clear              3263
2 rainy               309
3 other                15
4 dark                  2
5 foggy                 1</code></pre>
</div>
</div>
<section id="kde-by-weather-condition" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="kde-by-weather-condition"><span class="header-section-number">8.1</span> KDE by weather condition</h2>
<p>Unlike the day/night comparison, I let each weather subset use its <strong>own</strong> <code>bw.ppl()</code> bandwidth here rather than sharing one — the two groups differ in size by an order of magnitude (3,263 vs.&nbsp;309), and forcing the sparser rainy-day pattern through the same tight ~630 m bandwidth tuned for the dense clear-day pattern would just render as a scatter of unconnected dots, telling me nothing about where its own hotspots are.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>clear_ppp <span class="ot">&lt;-</span> <span class="fu">make_ppp</span>(acc_sf <span class="sc">|&gt;</span> <span class="fu">filter</span>(weather_condition <span class="sc">==</span> <span class="st">"clear"</span>))</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>rainy_ppp <span class="ot">&lt;-</span> <span class="fu">make_ppp</span>(acc_sf <span class="sc">|&gt;</span> <span class="fu">filter</span>(weather_condition <span class="sc">==</span> <span class="st">"rainy"</span>))</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>sigma_clear <span class="ot">&lt;-</span> <span class="fu">bw.ppl</span>(clear_ppp)</span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>sigma_rainy <span class="ot">&lt;-</span> <span class="fu">bw.ppl</span>(rainy_ppp)</span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>kde_clear <span class="ot">&lt;-</span> <span class="fu">density</span>(clear_ppp, <span class="at">sigma =</span> sigma_clear)</span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a>kde_rainy <span class="ot">&lt;-</span> <span class="fu">density</span>(rainy_ppp, <span class="at">sigma =</span> sigma_rainy)</span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-10"><a href="#cb71-10" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb71-11"><a href="#cb71-11" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_clear, <span class="at">main =</span> <span class="fu">paste0</span>(<span class="st">"Clear (n="</span>, clear_ppp<span class="sc">$</span>n, <span class="st">"), σ≈"</span>, <span class="fu">round</span>(sigma_clear), <span class="st">"m"</span>))</span>
<span id="cb71-12"><a href="#cb71-12" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_rainy, <span class="at">main =</span> <span class="fu">paste0</span>(<span class="st">"Rainy (n="</span>, rainy_ppp<span class="sc">$</span>n, <span class="st">"), σ≈"</span>, <span class="fu">round</span>(sigma_rainy), <span class="st">"m"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>KDE of accidents by weather condition, each panel on its own bandwidth and colour scale (see caveat below).</figcaption>
</figure>
</div>
</div>
</div>
<p>Because the two panels use different bandwidths (~630 m vs.&nbsp;~2,970 m) they aren’t directly comparable by eye in the way the day/night pair was — the rainy panel is inherently smoother just from having fewer points to work with. What <em>is</em> comparable: clear-weather accidents trace the road network tightly, with the sharpest hotspot at the same central interchange seen throughout this document; rainy-weather accidents, even smoothed over a much wider radius, still concentrate most heavily in the east-central part of the study area rather than spreading evenly across it — a different part of the network than clear-weather’s single dominant hotspot.</p>
</section>
<section id="formal-test" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="formal-test"><span class="header-section-number">8.2</span> Formal test</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>seg_weather <span class="ot">&lt;-</span> <span class="fu">seg_test</span>(</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>  acc_sf <span class="sc">|&gt;</span> <span class="fu">filter</span>(weather_condition <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"clear"</span>, <span class="st">"rainy"</span>)),</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"weather_condition"</span>, <span class="at">sigma =</span> <span class="dv">3000</span></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Computing observed value... Done.
Computing 99 simulated values... 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 
99.
Done.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>seg_weather</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Monte Carlo test of spatial segregation of types

data:  pm
T = 28.983, p-value = 0.01</code></pre>
</div>
</div>
</section>
<section id="interpretation-3" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="interpretation-3"><span class="header-section-number">8.3</span> Interpretation</h2>
<p><code>segregation.test()</code> returns <strong>p = 0.01</strong>, significant at the 5% level: clear-weather and rainy-weather accidents are not just different in volume (3,263 vs.&nbsp;309, tracking the fact that it isn’t raining most of the time) but occupy meaningfully different locations within the BMR. A plausible mechanism: rain doesn’t just add slickness uniformly everywhere, it exposes drainage, visibility and road-surface weaknesses that are concentrated in particular stretches of the network — so the “risky when wet” locations aren’t simply the same “risky all the time” locations scaled down. That’s a genuinely different, actionable finding from the first-order KDE alone, which only ever showed one dominant hotspot regardless of conditions.</p>
<hr>
</section>
</section>
<section id="summary" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Summary</h1>
<section id="key-findings" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="key-findings"><span class="header-section-number">9.1</span> Key findings</h2>
<ol type="1">
<li><strong>First-order</strong>: 2022 BMR accidents are heavily concentrated along the expressway/arterial network, with the sharpest hotspot at a central-eastern interchange in Bangkok. Both fixed and adaptive KDE agree on the location.</li>
<li><strong>Second-order</strong>: G, F, K and L function envelopes, plus a Clark-Evans R of 0.215 (p &lt; 2.2 × 10⁻¹⁶), all confirm the clustering is statistically real and holds from the shortest to the longest spatial scales tested — this is not an artefact of random chance.</li>
<li><strong>Spatio-temporal</strong>: STKDE (<code>sparr::spattemp.density()</code>, Chapter 6’s method) shows the hotspot’s location and shape reshaping continuously across the 24-hour cycle, and intensifying at the same location from October–December. The discrete formal test confirms day vs.&nbsp;night is a real spatial effect (<code>segregation.test</code> p ≈ 0.01) while weekday vs.&nbsp;weekend is not (p ≈ 0.34, volume-only).</li>
<li><strong>Value-added (weather)</strong>: rainy-weather accidents cluster in a significantly different part of the BMR than clear-weather accidents do (p ≈ 0.01), not just in smaller numbers.</li>
</ol>
</section>
<section id="limitations" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="limitations"><span class="header-section-number">9.2</span> Limitations</h2>
<ul>
<li>The BMR boundary is a name-based union of six provinces, not an official metro-area polygon — some edge effects near provincial borders are possible.</li>
<li>5% of BMR 2022 accident records have no coordinates and were dropped; if missingness isn’t spatially random (e.g.&nbsp;concentrated in a particular reporting agency or district), the hotspots shown here could be mildly biased.</li>
<li>321 points shared exact duplicate coordinates before jittering, most likely reflecting reporting granularity (nearest landmark/km-marker) rather than true identical locations — jittering fixes the statistical degeneracy but the true precision of any individual point is uncertain.</li>
<li>The day/night split (06:00–17:59 vs.&nbsp;18:00–05:59) is a fixed clock-time boundary, not tied to actual daylight — a reasonable approximation at this latitude but not exact.</li>
</ul>
</section>
<section id="data-sources-1" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="data-sources-1"><span class="header-section-number">9.3</span> Data sources</h2>
<ul>
<li>Thailand Road Accident 2019–2022 dataset — <a href="https://www.kaggle.com/datasets/thaweewatboy/thailand-road-accident-2019-2022">Kaggle</a></li>
<li>Thailand ADM1 province boundaries — <a href="https://www.geoboundaries.org/">geoBoundaries</a></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>